@echo off
CD FONTS
BC FONT /Es/Ah/E/X/Fs/O;
REM LINK /HI /FAR /NOE /NOD:BRT71EFR.LIB %1.OBJ,%1.EXE,,BCL71EFR.LIB+QBX.LIB+DTFMTER.LIB+DRACLIB2.LIB;
REM MOVE %1.EXE C:\FACT3\MAIN

CD ..
REM CALL CM3 ALT_ALBA
REM CALL CM3 ALT_FACT 
REM CALL CM3 ALT_PRES
REM CALL CM3 BCKUP
REM CALL CM3 BKHLP
REM CALL CM3 CLIENTS
REM CALL CM3 CLI_002
REM CALL CM3 CLI_003
REM CALL CM3 RES_001
REM CALL CM3 RES_002
REM CALL CM3 RES_003
REM CALL CM3 PROVEID
REM CALL CM3 STOCK
REM CALL CM3 STK_001
REM CALL CM3 STK_002
REM CALL CM3 RESET
REM CALL CM3 LAB_001
REM CALL CM3 HIS_ALBA
REM CALL CM3 HIS_CLI
REM CALL CM3 CLO_ANY
REM CALL CM3 CONFIG
