@ECHO OFF
CD FONTS
BC %1.BAS /G2/Lr/Es/D/E/X/O/Ot/Fs/W/Ah;
LINK /LI /FAR /EX /NOE /PACKFUNCTIONS /PACKCODE %1.OBJ,%1.EXE,,QBX.LIB+DRACLIB2.LIB;
DEL C:\FACT3\MAIN\%1.EXE
MOVE %1.EXE C:\FACT3\MAIN\%1.EXE
CD ..
