' ********************************************************************
'
' Fitxer....................: ALT_PRES.BAS
' Titol.....................: Modul per el mateniment de presupostos
'
' ********************************************************************
'
' Data inici................: 12/09/1997 17:30:00
' Data de la darrera revisi¢: 02/07/1998 17:08:00
' Autor.....................: Tomeu Cap¢ i Cap¢
' CopyRight.................: Smart Software 1993/97 (C)
' Codi......................: MS-BASIC 7.01 (PDS)
'
' ********************************************************************
' Notes: Modul nou per el Facturaci¢ 3.0
'
' ********************************************************************

DECLARE SUB CrearPRESUPOSTs (MAX!, DTO!, IVA!, AREANUM!, AREA3!, AREA2!, AREA4!, AREAST!, MAXFA!, MAXST!, MAXPR!, EDIT!, DH$, DEVI$)
DECLARE SUB FacturarAlbara (AREA!, AREANUM!, RG!, MAXFA!, MAXLIN!, DIRECC$)
DECLARE FUNCTION IniciaRef! (AREANUM!, R!, MARCAT!, REFOLD$)
DECLARE SUB GUARDAPRESUPO (RG!, MAXLIN!, F!, ASX!)
DECLARE SUB ReadCalculFactura ()
DECLARE SUB LLISTARPRESUPO (AREA5!, AREA2!, DEVI$)
DECLARE SUB SUMARPRESUPOS (MAXPR!, AREA2!)
DECLARE SUB IMPRIMIRPRESUPO (MAX!, DEVI$)
DECLARE SUB MASCALBA (MAX!)
DECLARE SUB MASCALBS ()
DECLARE SUB MASCLIST ()
DECLARE SUB CARREGARPRESUPO (R!, MAXLIN!)
DECLARE SUB OrdenarIndex (INDEX() AS ANY, MAXST!)
DECLARE SUB INITPRESUPO (MAXLIN!)
DECLARE SUB READCAPSALERA (MAXPR!, MAXCL!)
DECLARE SUB REPINTACAPSALERA (MAX!)
DECLARE SUB ReadObserva ()
DECLARE FUNCTION POSSAESPAI$ (CAD$, C!)
DECLARE FUNCTION CercarRecord% (CAMP$, INDEX() AS ANY, MAXST!, AREAST!)
DECLARE SUB PresupostsEdit (MAX!, DTO!, IVA!, DIRECC$, DIRCP$, DIRECI$, DH$, DP$, DEVI$, IMPRESORA!)


'$INCLUDE: 'QBX.BI'
'$INCLUDE: 'DATIM.BI'
'$INCLUDE: 'FORMAT.BI'
'$INCLUDE: 'C:\FACT3\FONTS\STRUCTS.BI'
'$INCLUDE: 'C:\FACT3\FONTS\FACTURA.BI'
'$INCLUDE: 'C:\FACT3\FONTS\PRESUPOS.BI'
'$INCLUDE: 'C:\FACT3\FONTS\STOCK.BI'
'$INCLUDE: 'C:\FACT3\FONTS\DRAC3.BI'
'$INCLUDE: 'C:\FACT3\FONTS\SDK_001.BI'
'$INCLUDE: 'C:\FACT3\FONTS\CONSTS.BI'

COMMON SHARED DIRECC$, DIRECCP$, DIRECCT$, DOCU$, DIRECCH$
COMMON SHARED AREA, AREA1, AREA2, AREA3, AREA4, AREA5, AREA8, AREA9, AREANDX
COMMON SHARED GUARDAT, MIDPOINT, MAXCL, MAXPR, MAXFA, R, EDIT
COMMON SHARED TOTAL, MAX, NOU, TROBAT, DEVICE$, DEVI$, UNIDAD$

'$DYNAMIC
DIM SHARED FLD(6) AS CN           ' CONFIGURACI¢ DE CAMPS
DIM SHARED MASC$(6)               ' CONFIGURACI¢ DE MASCARES
DIM SHARED LIN$(100, 7)           ' LINIES DEL PRESUPOST TEMPORAL
DIM SHARED OBS$(1)                ' LINIES D'OBSERVACIO
DIM SHARED COL(2, 1)
DIM SHARED CLIENT AS CLIENT
DIM SHARED CEMPRE AS CONTROLEMP
DIM SHARED TEXTOSMENUP(7) AS STRING
DIM SHARED COMMENT$(7, 0)
DIM SHARED STOCK AS STK
DIM SHARED PRESUPO AS PRESU
DIM SHARED LINPRES AS LINIAPRES
DIM SHARED FACTURA AS FACTU
DIM SHARED LINFAC AS LINIAFACT
DIM SHARED CAP AS CAPSALDOCS
DIM SHARED SPOOLIMP AS SPOOL
DIM SHARED ARCHIMP AS IMPRESORA
DIM SHARED CFG AS CONFIG
DIM SHARED CTRL AS CONTROL
DIM SHARED EMPRES AS EMPRESA
DIM SHARED USR AS USUARIS
DIM SHARED DOCNUM AS DN
DIM COLORS AS COLO
DIM PASO AS TRANS
DIM ANYS AS ANNO



'********************************************************************
'  Comprovaci¢ de la cridada del programa principal
'********************************************************************
	  ON ERROR GOTO ERRORS

	  TMP$ = ENVIRON$("TEMPORAL")
	  IF DIR$(TMP$ + "PASS.TMP") = "" THEN
	     BEEP: PRINT "ERROR: Al inicialitzar el m•dul de transpass 1"
	     SYSTEM
	  ELSE
	     DEF SEG = VARSEG(CFG)
	     BLOAD TMP$ + "PASS.TMP", VARPTR(CFG)
	     DEF SEG
	  END IF

	  DEF SEG = VARSEG(USR)
	  BLOAD TMP$ + "PASU.TMP", VARPTR(USR)
	  DEF SEG

	  DEF SEG = VARSEG(EMPRES)
	  BLOAD TMP$ + "PASE.TMP", VARPTR(EMPRES)
	  DEF SEG

	  DEF SEG = VARSEG(PASO)
	  BLOAD TMP$ + "PROT.TMP", VARPTR(PASO)
	  DEF SEG
	  CA$ = PASO.CLAU
	  CAD$ = PASO.APLICACIO
	  CA2$ = ""
	  FOR L% = 1 TO LEN(CAD$)
	      CA2$ = CA2$ + ENCRIPT$(MID$(CA$, L%, 1), L%)
	  NEXT

	  IF LTRIM$(RTRIM$(CA2$)) <> "ALT_PRES.EXE" THEN
	     tecla = Avis("ERROR:", "ENTRADA INCORRECTA AL PROGRAMA", "Pitji una tecla", 0)
	     SYSTEM
	  END IF

	  KILL TMP$ + "PASS.TMP"
	  KILL TMP$ + "PASU.TMP"
	  KILL TMP$ + "PASE.TMP"
	  KILL TMP$ + "PROT.TMP"



      UNIDAD$ = LTRIM$(RTRIM$(CFG.DRIVE))
      DBF$ = LTRIM$(RTRIM$(CFG.DDADE))             ' Assignar direcctoris
      SCR$ = LTRIM$(RTRIM$(CFG.DPANT))
      MSK$ = LTRIM$(RTRIM$(CFG.DRECU))
      HLP$ = LTRIM$(RTRIM$(CFG.DHELP))
      SYS$ = LTRIM$(RTRIM$(CFG.DSIST))

      DIRECCF$ = DBF$     ' Subdirecctori de les base de dades
      DIRECCP$ = SCR$ + "\"      ' Subdirecctori de les pantalles
      DIRECCR$ = MSK$ + "\"     ' Subdirecctori de mascares, errors, etc...
      DIRECCHE$ = HLP$ + "\"    ' Subdirecctori de ajuda
      DIRECCI$ = UNIDAD$ + "\IMPRESOR\"  ' Subdirecctori de les impresores
      DIRECCT$ = DBF$ + "TEXTOS\"
      DIRECCH$ = DBF$ + "HISTORIC\"

      MAXLINS = USR.MAXLINS
      MAXFAC = USR.LINALBA
      IVA = EMPRES.IVA
      DTO = EMPRES.DTO
      R = EMPRES.ANY
      DEV$ = LTRIM$(RTRIM$(USR.DEVICE))
      IMPRESORA = USR.IMPRESORA

      SetDirRecursos (DIRECCR$)
      SetFormatCC (34)

      AREAC = FREEFILE: OPEN DIRECCF$ + "COLORS.CFG" FOR RANDOM SHARED AS AREAC LEN = LEN(COLORS)
      GET AREAC, 1, COLORS
      COL(0, 0) = COLORS.COL(0, 0): COL(0, 1) = COLORS.COL(0, 1)
      COL(1, 0) = COLORS.COL(1, 0): COL(1, 1) = COLORS.COL(1, 1)
      COL(2, 0) = COLORS.COL(2, 0): COL(2, 1) = COLORS.COL(2, 1)
      CLOSE AREAC

      AREAA = FREEFILE: OPEN DIRECCF$ + "ANYS.DAT" FOR RANDOM SHARED AS AREAA LEN = LEN(ANYS)
      GET AREAA, R, ANYS

      DIRECCF$ = DIRECCF$ + ANYS.ANY + "\"
      CLOSE AREAA

      

      CALL PresupostsEdit(MAXFAC, INT(EMPRES.DTO), INT(EMPRES.IVA), DIRECCF$, DIRECCT$, DIRECCI$, DIRECCH$, DBF$, DEV$, IMPRESORA)
      SYSTEM

ERRORS:
      IF ShowError = 1 THEN
	 RESUME NEXT
      ELSE
	 RESET
	 SYSTEM
      END IF

SUB CARREGARPRESUPO (R, MAXLIN)
    SHARED LIN$()

    GET AREA3, R, LINPRES
    FOR J = 1 TO MAXLIN
	LIN$(J, 1) = LINPRES.LINIA(J).CODART
	LIN$(J, 2) = LINPRES.LINIA(J).CONCEPTE
	LIN$(J, 3) = STR$(LINPRES.LINIA(J).PREU)
	LIN$(J, 4) = STR$(LINPRES.LINIA(J).QUANTI)
	LIN$(J, 7) = STR$(LINPRES.LINIA(J).DTO)
	LIN$(J, 5) = STR$(LINPRES.LINIA(J).IMPORT)
	LIN$(J, 6) = LINPRES.LINIA(J).MARCAR
    NEXT
    GET AREA2, R, PRESUPO
END SUB

FUNCTION CercarRecord% (CAMP$, INDEX() AS INDEXTYPE, MAXST, AREAST) STATIC
	 SHARED MIDPOINT

	 TOPRECORD = MAXST - 1
	 BottomRecord = 1

	 DO UNTIL (TOPRECORD < BottomRecord)
	    MIDPOINT = (TOPRECORD + BottomRecord) \ 2
	    TEST$ = RTRIM$(ForaEspai$(INDEX(MIDPOINT).CODI))

	    IF TEST$ = CAMP$ THEN
	       EXIT DO
	    ELSEIF CAMP$ > TEST$ THEN
	       BottomRecord = MIDPOINT + 1
	    ELSE
	       TOPRECORD = MIDPOINT - 1
	    END IF
	 LOOP

	 IF TEST$ = CAMP$ THEN
	    GET AREAST, INDEX(MIDPOINT).REGISTRE, STOCK
	    CercarRecord% = TRUE
	 ELSE
	    CercarRecord% = FALSE
	 END IF
END FUNCTION

SUB CrearPRESUPOSTs (MAX, DTO, IVA, AREANUM, AREA3, AREA2, AREA4, AREAST, MAXFA, MAXST, MAXPR, EDIT, DH$, DEVI$)
       SHARED LIN$(), TEXTOSMENUP() AS STRING
       SHARED UNIDAD$, DIRECCH$, DIRECC$

'*********************************************************************
' INDEXAR FITXER DEL STOCK
'*********************************************************************
       COLOR COL(0, 0), COL(0, 1): FINESTRA 10, 30, 14, 47, 1, CAIXA1
       COLOR 31, COL(0, 1): LOCATE 11, 31: PRINT "ESPERA UN MOMENT"
       COLOR 31, COL(0, 1): LOCATE 13, 31: PRINT " PROCESSANT ... "
       DIM INDEX(1 TO MAXST) AS INDEXTYPE
       DIM M$(2)
       DIM NDXFILE AS INDEXTYPE
       GOSUB CARREGARINDEX

'*********************************************************************

       FLD(1).XCAMP = 2: FLD(1).LON = 18: FLD(1).TIPUS = ASCI: FLD(1).MASK = STRING$(18, "X")
       FLD(2).XCAMP = 21: FLD(2).LON = 40: FLD(2).TIPUS = ASCI: FLD(2).MASK = STRING$(40, "X")
       FLD(3).XCAMP = 51: FLD(3).LON = 9: FLD(3).TIPUS = NUM: FLD(3).MASK = "999999999"
       FLD(4).XCAMP = 61: FLD(4).LON = 8: FLD(4).TIPUS = NUM: FLD(4).MASK = "99999.99"

'*********************************************************************
' INICIAR MASCARES DELS CAMPS
'*********************************************************************
       MASC$(1) = "\              \"             ' CODI ARTICLE
       MASC$(2) = "\" + SPACE$(27) + "\"         ' CONCEPTE
       MASC$(3) = "#,##,###"                     ' PREU
       MASC$(4) = "#,###.##"                     ' QUANTITAT
       MASC$(5) = "##,###,###"                   ' IMPORT
       MASCTOTAL$ = "##,###,###.##"              ' TOTAL

'*********************************************************************
' MIRA A VEURA SI HA DE EDITAR ALGUN REGISTRE
'*********************************************************************
       GetBackground 1, 1, 24, 79, RESBUF$
       TROBAT$ = "*"
       IF EDIT = 1 THEN
	  CALL CARREGARPRESUPO(R, MAX): Q = R
	  IF PRESUPO.DOCUMENT = "P" THEN DOCU$ = "PRESUPOST"
	  IF PRESUPO.DOCUMENT = "F" THEN
	     BEEP: tecla = Avis("AVIS:", "Presupost ja facturat, no es pot tornar a modificar", "Pitji una tecla", 0)
	     EXIT SUB
	  END IF
       ELSE
	  
	  FOR Q = 1 TO MAXPR - 1
	      GET AREA2, Q, PRESUPO
	      IF PRESUPO.MARCAT = "*" THEN
		 TROBAT$ = "Z"
		 EXIT FOR
	      END IF
	  NEXT

	  IF TROBAT$ = "Z" THEN   ' SI HA TROBAT ALGUN REGISTRE MARCAT
	     R = Q
	  ELSE
	     R = MAXPR
	  END IF
	  DOCU$ = "PRESUPOST"

	  INITPRESUPO (MAX)    ' POSSA A PUNT LES VARIABLES DEL PRESUPO
	  LIN$(1, 6) = "-"     ' DEIXA UNA LINIA DISPONIBLE PER EDITAR-LA
       END IF

'*********************************************************************
' INICIALITZAR VALORS DE L'PRESUPO
'*********************************************************************
       '
       ' INICIA N£MERO DE REFERŠNCIA
       '
       IF EDIT = 0 THEN
	  REF$ = "0000000-P": ALB$ = LTRIM$(STR$(R)): L2 = 7
	  FOR L = LEN(ALB$) TO 1 STEP -1
	      MID$(REF$, L2, 1) = MID$(ALB$, L, 1): L2 = L2 - 1
	  NEXT
	  PRESUPO.REFPRESUPO = REF$
       END IF

       MASCALBA (MAX)                               ' PINTAR MASCARA
       IF EDIT = 1 THEN GOSUB LLISTA.TROS.PRESUPO   ' SI L'ALBARA S'HA DE MODIFICAR QUE LLISTI UN TROS DEL ALBARA
       CALL READCAPSALERA(MAXPR, MAXCL)             ' DEMANAR DADES DE LA CAP€ALERA

       LOCATE 23, 2: PRINT "ENTER=EDITAR LINIA    ESC=ANULAR    SUPR=SUPRIMIR LINIA";
       LOCATE 24, 2: PRINT "<" + CHR$(25) + ">= BAIXAR           <" + CHR$(24) + ">= PUJAR    CTRL+F=ACABAR L'ALBAR…";

       L = 1: C = 1: YC = 9: MODIF = 0: GUARDAT = 0
       GOSUB MARCACAMP      ' MARCA CAMP DE CODI ARTICLE

       DO
	 T$ = INKEY$
	 SELECT CASE T$
		CASE CHR$(0) + "S"
		     GOSUB BORRA
		CASE CHR$(0) + "H"
		     GOSUB PUJA
		CASE CHR$(0) + "P"
		     GOSUB BAIXA
		CASE CHR$(13)
		     GOSUB LLEGEIXCAMP
		     GOSUB MARCACAMP
		CASE CHR$(6)
		     GetBackground 1, 1, 24, 79, RESBUF$
		     IF MODIF = 0 THEN
			ReadObserva                  ' EDITAR OBSERVACIONS
			PRESUPO.TOTALBRUT = TOTAL
			PRESUPO.DTO = DTO
			PRESUPO.TIPOIVA = IVA
			ReadCalculFactura            ' CALCULAR L'IVA I EL DTO DE LA FACTURA
		     ELSE
			IF MODIF = 1 THEN ReadCalculFactura  ' CALCULAR L'IVA I EL DTO DE LA FACTURA
		     END IF

		     DO
		       TEXTOSMENUP(1) = " MODIFICAR CAP€ALERA    "
		       TEXTOSMENUP(2) = " MODIFICAR LINIES       "
		       TEXTOSMENUP(3) = " MODIFICAR OBSERVACIONS "
		       TEXTOSMENUP(4) = " IMPRIMIR PRESUPOST     "
		       TEXTOSMENUP(5) = " GUARDAR PRESUPOST      "
		       TEXTOSMENUP(6) = STRING$(24, "Ä")
		       TEXTOSMENUP(7) = " FACTURAR PRESUPOST     "
		       COLOR COL(1, 1), CCT
		       CALL MenuBar(TEXTOSMENUP(), COMMENT$(), 0, CASO%, 14, 23, LEN(TEXTOSMENUP(1)), 7, COL(0, 0), COL(0, 1), COL(1, 0), COL(1, 1))
		       SELECT CASE CASO%
			      CASE 1
				   CALL READCAPSALERA(MAXPR, MAXCL)
			      CASE 2
				   MODIF = 1
				   PutBackground 1, 1, RESBUF$
				   REPINTACAPSALERA (MAXPR)
				   EXIT DO
			      CASE 3
				   PutBackground 1, 1, RESBUF$
				   REPINTACAPSALERA (MAXPR)
				   ReadObserva
			      CASE 4
				   CALL IMPRIMIRPRESUPO(MAX, DEVI$)
			      CASE 5
				   IF EDIT = 1 THEN
				      RG = Q
				   ELSE
				      RG = MAXPR
				      IF TROBAT$ = "Z" THEN RG = Q
				   END IF
				   CALL GUARDAPRESUPO(RG, MAX, 0, ASX)
			      CASE 7
				   IF EDIT = 1 THEN
				      RG = Q
				   ELSE
				      RG = MAXPR
				      IF TROBAT$ = "Z" THEN RG = Q
				   END IF

'                                   CALL GUARDAPRESUPO(RG, MAX, 1, ASX)
				   IF ASX <> 999 THEN
				      CALL FacturarAlbara(AREA, AREANUM, RG, MAXFA, MAX, DIRECC$)
				   END IF
			      CASE 999
				   IF NOU = 2 THEN
				      ERASE INDEX
				      NOU = 9
				      EXIT SUB
				   ELSE
				      IF NOU = 3 THEN
					 ERASE INDEX
					 GOSUB GUARDADAR.NUMERO.ALBARA
					 PutBackground 1, 1, RESBUF$
					 EXIT SUB
				      END IF
				   END IF
				   ERASE INDEX
				   GOSUB GUARDADAR.NUMERO.ALBARA
			      CASE ELSE
		       END SELECT
		     LOOP
		CASE CHR$(27)
		     IF NOU = 2 THEN        ' SI ES EL PRIMER PRESUPO QUE ES FA
			ERASE INDEX
			NOU = 9
			PutBackground 1, 1, RESBUF$
			EXIT SUB
		     ELSE
			ERASE INDEX
			EXIT SUB
		     END IF
		CASE ELSE
		     COLOR COL(2, 0), COL(0, 1): LOCATE 20, 2: PRINT "Linia: "; : COLOR COL(2, 0) XOR COL(2, 1): PRINT L;
		     LOCATE 20, 53: PRINT VAL(LIN$(L, 7));
		     LOCATE 20, 20: PRINT LIN$(L, 6)
	 END SELECT
       LOOP

'*********************************************************************
' CONTROL DEL CURSOR PER L'PRESUPO
'*********************************************************************

BORRA:
	 IMPORT = VAL(LIN$(L, 5))
	 TOTAL = TOTAL - IMPORT
	 IF TOTAL < 0 THEN TOTAL = 0

	 FOR CB = 1 TO 4
	     X = FLD(CB).XCAMP: LE = FLD(CB).LON
	     LIN$(L, CB) = SPACE$(LE)
	     COLOR COL(1, 1), CCT: LOCATE YC, X: PRINT STRING$(LE, " ");
	 NEXT
	 
	 IF LIN$(L, 6) <> "-" THEN
	    LIN$(L, 6) = "*"
	 END IF
	 LIN$(L, 5) = ""
	 IF LIN$(1, 6) = "-" THEN LIN$(1, 6) = "*"

	 LOCATE YC, 61: PRINT "        "
	 LOCATE YC, 70: PRINT "          "
	 COLOR COL(0, 0) XOR COL(0, 1), COL(0, 1)
	 LOCATE 20, 67: PRINT USING MASCTOTAL$; TOTAL
	 GOSUB MOSTRA
	 GOSUB MARCACAMP
	 RETURN

PUJA:
	 IF L = 1 THEN SOUND 50, .5: tecla = Avis("AVIS:", "Principi del presupost", "Pitji una tecla...", 0): RETURN
	 X = FLD(C).XCAMP: LE = FLD(C).LON: T = FLD(C).TIPUS
	 COLOR COL(0, 0), COL(0, 1): LOCATE YC, X: PRINT STRING$(LE, " ");
	 LOCATE YC, X, 0: PRINT LIN$(L, C)
	 C = 1: YC = YC - 1: L = L - 1
	 LOCATE 20, 20: PRINT "       ";

	 IF YC < 9 THEN
	    ScrollDown 17, 78, 8, 1, 1
	    YC = 9
	    GOSUB MOSTRA
	    LOCATE 20, 20: PRINT "  AMUNT";
	 END IF
	 
	 GOSUB MOSTRA
	 GOSUB MARCACAMP
	 RETURN

BAIXA:
	 IF L = MAX THEN SOUND 50, .5: tecla = Avis("AVIS:", "Final del presupost", "Pitji una tecla...", 0): RETURN
	 X = FLD(C).XCAMP: LE = FLD(C).LON: T = FLD(C).TIPUS
	 COLOR COL(0, 0), COL(0, 1): LOCATE YC, X: PRINT STRING$(LE, " ");
	 LOCATE YC, X: PRINT LIN$(L, C)
	 LOCATE YC, X, 0
	 C = 1: YC = YC + 1: L = L + 1
	 LOCATE 20, 20: PRINT "       ";
	 IF YC > 18 THEN
	    ScrollUp 17, 78, 8, 1, 1
	    YC = 18
	    GOSUB MOSTRA
	    LOCATE 20, 20: PRINT "  AVALL";
	 END IF
	 
	 GOSUB MOSTRA
	 GOSUB MARCACAMP
	 RETURN

MOSTRA:
	 COLOR COL(0, 0), COL(0, 1)
	 LOCATE YC, 2: PRINT SPACE$(18); "º"; SPACE$(29); "º"; SPACE$(9); "º"; SPACE$(8); "º"; SPACE$(10)
	 IF LIN$(L, 6) = "*" OR LIN$(L, 6) = "-" THEN
	    LOCATE YC, 2: PRINT USING MASC$(1); LIN$(L, 1)
	    LOCATE YC, 2 + 18 + 1: PRINT USING MASC$(2); LIN$(L, 2)
	    LOCATE YC, 52: PRINT USING MASC$(3); VAL(LIN$(L, 3))
	    LOCATE YC, FLD(4).XCAMP: PRINT USING MASC$(4); VAL(LIN$(L, 4))
	    LOCATE YC, 70: PRINT USING MASC$(5); VAL(LIN$(L, 5))
	    LOCATE 20, 53: PRINT VAL(LIN$(L, 7))
	 END IF
	 RETURN

MARCACAMP:
	 X = FLD(C).XCAMP: LE = FLD(C).LON: T = FLD(C).TIPUS
	 COLOR COL(1, 0), COL(1, 1): LOCATE YC, X: PRINT STRING$(LE, " ");
	 LOCATE YC, X: PRINT LIN$(L, C)
	 LOCATE YC, X, 0
	 RETURN

'*********************************************************************
' RUTINA PER LLEGIR ELS CAMPS D'UNA LINIA
'*********************************************************************

LLEGEIXCAMP:
     COLOR COL(0, 0), COL(0, 1)
     LOCATE 23, 2: PRINT SPACE$(70);
     LOCATE 24, 2: PRINT SPACE$(70);
     LOCATE 22, 2: PRINT SPACE$(70);
     IF LIN$(L, 6) <> "*" AND LIN$(L, 6) <> "-" THEN
	LOCATE 23, 2: PRINT "VES PER ORDRE !!!": BEEP
	LOCATE 23, 2: PRINT "ENTER=EDITAR LINIA    ESC=ANULAR    SUPR=SUPRIMIR LINIA";
	LOCATE 24, 2: PRINT "<" + CHR$(25) + ">= BAIXAR           <" + CHR$(24) + ">= PUJAR    CTRL+F=ACABAR L'ALBAR…";
	RETURN
     END IF
     LOCATE 23, 2: PRINT "ENTER=PASSAR A L'ALTRE CAMP      ESC=SORTIR"
     SALE = 0
     TROBAT = 0
      DO

	 SetMaxCamps 0: SetColorCamp 0, COL(1, 0), COL(1, 1), COL(0, 0), COL(0, 1), COL(2, 0), COL(2, 1)
	 X = FLD(C).XCAMP: T = FLD(C).TIPUS: M$ = LTRIM$(RTRIM$(FLD(C).MASK))
	 SetInitCamp 0, YC, X, T, 0, M$, ""
	 InsertValueCamp 0, LIN$(L, C): VELL$ = LIN$(L, C)

	 VALUE = ReadCamp(0)
	 SELECT CASE VALUE
		CASE F1
		     'SHELL "BKHLP PRESUPOS"
		CASE F2
		     IF C = 1 THEN GOSUB LLISTA.STOCK
		CASE F3 TO F10
		     SOUND 50, .5
		CASE SALIR
		     LOCATE 23, 2: PRINT "ENTER=EDITAR LINIA    ESC=ANULAR    SUPR=SUPRIMIR LINIA";
		     LOCATE 24, 2: PRINT "<" + CHR$(25) + ">= BAIXAR           <" + CHR$(24) + ">= PUJAR    CTRL+F=ACABAR L'ALBAR…";
		     X = FLD(1).XCAMP
		     RETURN
		CASE ELSE
	 END SELECT

	 LIN$(L, C) = ValueCamp$(0)
	 CAMPTEMP$ = ForaEspai$(ValueCamp$(0))

	    IF C = 1 THEN
	       IF CercarRecord%(CAMPTEMP$, INDEX(), MAXST, AREAST) THEN
		  IF STOCK.MARCAT <> "*" THEN
		     LIN$(L, 2) = STOCK.DESCRIPCIO
		     IF STOCK.EXISTENCIA < STOCK.STOCKMIN THEN
			COLOR 27: BEEP: LOCATE 22, 2: PRINT "Aquest article est… baix minims            "
		     ELSE
			IF STOCK.EXISTENCIA = 0 THEN
			   COLOR 27: BEEP: LOCATE 22, 2: PRINT "Aquest article est… amb existŠncies 0"
			END IF
		     END IF
		     TROBAT = 999
		  END IF
	       END IF
	    END IF

	    IF C = 4 THEN
	       IF TROBAT = 999 THEN                        ' RESTAR AL STOCK
		  LOCK AREAST, INDEX(MIDPOINT).REGISTRE
		  GET AREAST, INDEX(MIDPOINT).REGISTRE, STOCK
		  SAC = STOCK.EXISTENCIA - VAL(LIN$(L, 4))
		  GOSUB ACTUALIZHISTORIC
		  STOCK.EXISTENCIA = SAC
		  PUT AREAST, INDEX(MIDPOINT).REGISTRE, STOCK
		  UNLOCK AREAST, INDEX(MIDPOINT).REGISTRE
	       END IF
	    END IF

	 IF T = ASCI THEN
	    LOCATE YC, X: PRINT USING MASC$(C); ValueCamp$(0)
	 ELSE
	    LOCATE YC, X: PRINT USING MASC$(C); VAL(ValueCamp$(0))
	 END IF

	 DeleteCamp 0
	 C = C + 1
	 GOSUB MOSTRA
	 IF C = 3 THEN
		  M$(1) = "Preu Venda ": M$(2) = "Preu Compra"
		  'IF TESTSCREEN = &HB000 THEN SAVESCREEN DIRECCP$ + "MFACTUR.SCR", 0, 4000 ELSE CALL SAVESCRN
		  GetBackground 1, 1, 24, 79, BUF$
		  CALL Menu2(M$(), CASO%, INT(YC), INT(FLD(C).XCAMP), 13, 2, COL(0, 0), COL(0, 1), COL(1, 0), COL(1, 1))
		  PutBackground 1, 1, BUF$
		  'IF TESTSCREEN = &HB000 THEN RESTORESCREEN DIRECCP$ + "MFACTUR.SCR", 0 ELSE CALL RESTSCRN
		  SELECT CASE CASO%
			 CASE 1
			      LIN$(L, 3) = LTRIM$(STR$(STOCK.PVPACONSE))
			      LIN$(L, 7) = ""
			 CASE 2
			      LIN$(L, 3) = LTRIM$(STR$(STOCK.PREU))
			      LIN$(L, 7) = ""
			 CASE 999
			      LIN$(L, 3) = LTRIM$(STR$(STOCK.PREU))
			      LIN$(L, 7) = ""
			 CASE ELSE
		  END SELECT

	 END IF
	 
	 IF C = 5 THEN
	    SetMaxCamps 0: SetColorCamp 0, COL(1, 0), COL(1, 1), COL(0, 0), COL(0, 1), COL(2, 0), COL(2, 1)
	    SetInitCamp 0, 20, 53, NUM, 0, "999", ""
	
	    DeleteCamp 0
	    InsertValueCamp 0, LIN$(L, 7)
	    IF ReadCamp(0) = SALIR THEN BEEP
	    LIN$(L, 7) = ValueCamp$(0)

	    PREU = VAL(LIN$(L, 3))
	    QUANT = VAL(LIN$(L, 4))
	    DESCOMPTE = VAL(LIN$(L, 7))

	    IMPORT = QUANT * PREU - ((QUANT * PREU) * DESCOMPTE) / 100

	    LIN$(L, C) = STR$(IMPORT)

	    SUBTOTAL = 0        ' TORNA A RECALCULAR ELS TOTALS
	    FOR J = 1 TO MAX
		SUBTOTAL = SUBTOTAL + VAL(LIN$(J, 5))
	    NEXT

	    TOTAL = SUBTOTAL

	    LOCATE YC, 70: PRINT USING MASC$(5); IMPORT
	    COLOR COL(0, 0) XOR COL(0, 1), COL(0, 1)
	    LOCATE 20, 67: PRINT USING MASCTOTAL$; TOTAL
	    
	    IF L = MAX THEN
	       IF LIN$(L, 6) = "-" THEN LIN$(L, 6) = "*"
	    ELSE
	       IF LIN$(L, 6) = "-" THEN
		  LIN$(L, 6) = "*"
	       END IF
	       IF LIN$(L + 1, 6) <> "-" AND LIN$(L + 1, 6) <> "*" THEN
		  LIN$(L + 1, 6) = "-"
	       END IF
	    END IF

	    IF YC = 18 THEN
	       ScrollUp 17, 78, 8, 1, 1
	       YC = 18: L = L + 1: C = 1: SALE = 1
	       GOSUB MOSTRA
	    ELSE
	       C = 1: L = L + 1: YC = YC + 1: SALE = 1
	    END IF
	 END IF
      LOOP UNTIL SALE = 1
      COLOR COL(0, 0), COL(0, 1): LOCATE 22, 2: PRINT SPACE$(70);
      LOCATE 23, 2: PRINT "ENTER=EDITAR LINIA    ESC=ANULAR    SUPR=SUPRIMIR LINIA"
      LOCATE 24, 2: PRINT "<" + CHR$(25) + ">= BAIXAR           <" + CHR$(24) + ">= PUJAR    CTRL+F=ACABAR L'ALBAR…";
      RETURN

LLISTA.TROS.PRESUPO:
      YC = 9
      FOR L = 1 TO 10
	  GOSUB MOSTRA
	  YC = YC + 1
      NEXT
      TOTAL = PRESUPO.TOTALBRUT
      COLOR COL(0, 0) XOR COL(0, 1), COL(0, 1)
      LOCATE 20, 67: PRINT USING MASCTOTAL$; TOTAL
      RETURN

LLISTA.STOCK:
      
      RETURN

GUARDADAR.NUMERO.ALBARA:
      GetBackground 1, 1, 24, 79, FACTU$
      IF GUARDAT = 999 THEN
	 IF EDIT = 0 THEN
	    IF TROBAT$ <> "Z" THEN
	       CEMPRE.MAXPRESUPO = MAXPR + 1
	       PUT AREA, 1, CEMPRE
	       MAXPR = CEMPRE.MAXPRESUPO
	       EXIT SUB
	      
	    END IF
	 END IF
      ELSE
	 COLOR COL(0, 0), COL(0, 1)
	 FINESTRA 10, 20, 14, 65, 1, CAIXA1
	 COLOR 28, COL(0, 1)
	 LOCATE 11, 21: PRINT "        El presupost no est… guardat": COLOR 14
	 LOCATE 13, 21: PRINT "    ¨ Estas segur que vols sortir (S/N) ?"
	   DO
	     T$ = INKEY$
	   LOOP UNTIL T$ <> ""
	   SELECT CASE UCASE$(T$)
		  CASE "S"
		       PutBackground 1, 1, RESBUF$
		       EXIT SUB
		  CASE "N"
		       PutBackground 1, 1, FACTU$
		       RETURN
		  CASE ELSE
		       PutBackground 1, 1, FACTU$
		       RETURN
	   END SELECT
      END IF
      RETURN

CARREGARINDEX:
      FOR RI = 1 TO MAXST                     ' COL.LOCAR A MEM•RIA L'INDEX
	  GET AREANDX, RI, NDXFILE
	  INDEX(RI).REGISTRE = NDXFILE.REGISTRE
	  INDEX(RI).CODI = NDXFILE.CODI
      NEXT
      RETURN

ACTUALIZHISTORIC:
       RETURN
END SUB

SUB FacturarAlbara (AREA, AREANUM, RG, MAXFA, MAXLIN, DIRECC$) STATIC
      SHARED DIRECCF$
    
      AREA8 = FREEFILE: OPEN DIRECCF$ + "FACTURES.CAB" FOR RANDOM SHARED AS AREA8 LEN = LEN(FACTURA)
      AREA9 = FREEFILE: OPEN DIRECCF$ + "FACTURES.LIN" FOR RANDOM SHARED AS AREA9 LEN = LEN(LINFAC)

      FOR Q = 1 TO MAXFA - 1
	  GET AREA8, Q, FACTURA
	  IF FACTURA.MARCAT = "*" THEN
	     TROBAT$ = "Z"
	     EXIT FOR
	  END IF
      NEXT

      IF TROBAT$ = "Z" THEN   ' SI HA TROBAT ALGUN REGISTRE MARCAT
	 R = Q
      ELSE
	 R = MAXFA
	 MAXFA = MAXFA + 1
	 GET AREA, 1, CEMPRE
	 CEMPRE.MAXFACTURA = MAXFA
	 PUT AREA, 1, CEMPRE
      END IF

	   TIPUS% = IniciaRef(AREANUM, R, FALSE, "")
	   IF TIPUS% = 999 OR TIPUS% = 888 THEN
	      CLOSE AREA8, AREA9
	      EXIT SUB
	   END IF
	   FACTURA.DOCUMENT = "F"
	   FACTURA.DADA = FormatD$(Now#, "dd/mm/yy")
	   FACTURA.CODCLIENT = PRESUPO.CODCLIENT
	   FACTURA.PERSONA.NOM = PRESUPO.PERSONA.NOM
	   FACTURA.PERSONA.COGNOMS = PRESUPO.PERSONA.COGNOMS
	   FACTURA.PERSONA.DNI = PRESUPO.PERSONA.DNI
	   FACTURA.PERSONA.DIRECCIO = PRESUPO.PERSONA.DIRECCIO
	   FACTURA.PERSONA.POBLACIO = PRESUPO.PERSONA.POBLACIO
	   FACTURA.PERSONA.TELEFON1 = PRESUPO.PERSONA.TELEFON1
	   FACTURA.PERSONA.TELEFON2 = PRESUPO.PERSONA.TELEFON2
	   FACTURA.PERSONA.CPOSTAL = PRESUPO.PERSONA.CPOSTAL
	   FACTURA.PERSONA.DTO = PRESUPO.PERSONA.DTO
	   FACTURA.PERSONA.FORMAPAGO = PRESUPO.PERSONA.FORMAPAGO
	   FACTURA.DTO = PRESUPO.DTO
	   FACTURA.TIPOIVA = PRESUPO.TIPOIVA
	   FACTURA.TIPOIVA = PRESUPO.TIPOIVA
	   FACTURA.BASEIMPONIBLE = PRESUPO.BASEIMPONIBLE
	   FACTURA.TOTALBRUT = PRESUPO.TOTALBRUT
	   FACTURA.TOTALIVA = PRESUPO.TOTALIVA
	   FACTURA.TOTALNET = PRESUPO.TOTALNET
	   FACTURA.OBSERVA(1) = "Factura corresponent al presupost N§:" + PRESUPO.REFPRESUPO
	   FACTURA.OBSERVA(2) = "De la data " + PRESUPO.DADA
	   FACTURA.MARCAT = " "
	   PUT AREA8, R, FACTURA

	   FOR J = 1 TO MAXLIN
	       LINFAC.LINIA(J).REFALBARAN = PRESUPO.REFPRESUPO
	       LINFAC.LINIA(J).CODART = LIN$(J, 1)
	       LINFAC.LINIA(J).CONCEPTE = LIN$(J, 2)
	       LINFAC.LINIA(J).PREU = VAL(LIN$(J, 3))
	       LINFAC.LINIA(J).QUANTI = VAL(LIN$(J, 4))
	       LINFAC.LINIA(J).DTO = VAL(LIN$(J, 7))
	       LINFAC.LINIA(J).IMPORT = VAL(LIN$(J, 5))
	       LINFAC.LINIA(J).MARCAR = LIN$(J, 6)
	   NEXT
	   PUT AREA9, R, LINFAC

	   GET AREANUM, 1, DOCNUM
	   DOCNUM.FACTNUM(TIPUS%).MAXFACT = DOCNUM.FACTNUM(TIPUS%).MAXFACT + 1
	   PUT AREANUM, 1, DOCNUM
    
	   Avis.Sonor (1)

	   tecla = Avis("AVIS:", "El presupost s'ha facturat sense problemes", "Pitji una tecla per a continuar...", 0)

	   CLOSE AREA8, AREA9
END SUB

SUB GUARDAPRESUPO (RG, MAXLIN, F, ASX)

    IF PRESUPO.MARCAT = "*" THEN PRESUPO.MARCAT = " "
    IF F = 1 THEN
       IF PRESUPO.DOCUMENT = "F" THEN
	  BEEP: tecla = Avis("AVIS:", "Albar… ja facturat", "Pitja una tecla...", 0)
	  ASX = 999
	  EXIT SUB
       END IF
       PRESUPO.DOCUMENT = "F": NOU = 3
    ELSE
       PRESUPO.DOCUMENT = "A": NOU = 3
    END IF
    
    PUT AREA2, RG, PRESUPO
    FOR J = 1 TO MAXLIN
	LINPRES.LINIA(J).CODART = LIN$(J, 1)
	LINPRES.LINIA(J).CONCEPTE = LIN$(J, 2)
	LINPRES.LINIA(J).PREU = VAL(LIN$(J, 3))
	LINPRES.LINIA(J).QUANTI = VAL(LIN$(J, 4))
	LINPRES.LINIA(J).DTO = VAL(LIN$(J, 7))
	LINPRES.LINIA(J).IMPORT = VAL(LIN$(J, 5))
	LINPRES.LINIA(J).MARCAR = LIN$(J, 6)
    NEXT
    PUT AREA3, RG, LINPRES
    GUARDAT = 999

END SUB

SUB IMPRIMIRPRESUPO (MAX, DEVI$)
    SHARED DIRECCT$
    DIM CONFIG$(4)
    DIM MENU(5) AS STRING

    IMPR$ = "IMPRIMEIX_TEXTE"
    MASC$(4) = "##,###.#"                     ' QUANTITAT
    MASC$(5) = "##,###,###"                   ' IMPORT
    MASCTOTAL$ = "##,###,###.##"              ' TOTAL

    CONFIG$(0) = " CODI ARTICLE      CONCEPTE                  QUANT.     PREU  DTO%     IMPORT"
    CONFIG$(1) = "         QUANTITAT CONCEPTE                       IMPORT"
    CONFIG$(2) = " CODI ARTICLE     CONCEPTE                  QUANT.    PREU  DTO%          IMPORT"
    CONFIG$(3) = " CODI ARTICLE   CONCEPTE                 QUANT.  PREU  % IMPORT"
    CONFIG$(4) = " CODI ARTICLE      CONCEPTE                  QUANT.     PREU  DTO%     IMPORT"

    MENU(1) = "  DOCUMENT TIPUS PER DEFECTE      "
    MENU(2) = "  DOCUMENT TIPUS 1                "
    MENU(3) = "  DOCUMENT AMB PAPER PRE-IMPRES   "
    MENU(4) = "  DOCUMENT COMPACTAT (RESGUARDS)  "
    MENU(5) = "  DOCUMENT TIPUS COMPACTE         "
    
    GetBackground 1, 1, 24, 79, FACTU$
    CALL Menu2(MENU(), CASO%, 17, 23, LEN(MENU(1)) + 2, 5, COL(0, 0), COL(0, 1), COL(1, 0), COL(1, 1))
    IF CASO% = 999 THEN
       PutBackground 1, 1, FACTU$
       ERASE MENU, CONFIG$
       EXIT SUB
    END IF

    MODO = CASO% - 1: OPC = CASO% - 1

    COLOR 15, 9: FINESTRA 10, 30, 14, 45, 1, CAIXA1
    COLOR 31, 9: LOCATE 11, 31: PRINT "ACTUALITZANT"
    COLOR 31, 9: LOCATE 13, 31: PRINT "  FITXERS   "
    
    AREATXT = FREEFILE
    OPEN DIRECCT$ + "PRESUPO.TXT" FOR OUTPUT SHARED AS AREATXT

    PAG = 1
    GET AREA5, 1, CAP
    GOSUB CAPSA
    IF CASO% = 3 THEN
       MAXLINS = 25
    ELSE
       IF CASO% = 5 THEN
	  MAXLINS = 17
       ELSE
	  MAXLINS = 29
       END IF
    END IF
    LI = 1: L = 1

    DO
	IF LI = MAXLINS THEN
	   IF CASO% = 5 THEN
	      FOR LA = LI TO MAXLINS: PRINT #AREATXT, "": NEXT
	      PRINT #AREATXT, RTRIM$(ARCHIMP.NOCOMPRIMIDO) + STRING$(78, "Ä")
	      PRINT #AREATXT, "Suma i continua..."
	      PRINT #AREATXT, RTRIM$(ARCHIMP.NOCOMPRIMIDO) + STRING$(78, "Ä")
	      FOR SALT = 1 TO 9
		  PRINT #AREATXT, ""
	      NEXT
	      PAG = PAG + 1
	      GOSUB CAPSA
	   ELSE
	      FOR LA = LI TO MAXLINS: PRINT #AREATXT, "": NEXT
	      PRINT #AREATXT, RTRIM$(ARCHIMP.NOCOMPRIMIDO) + STRING$(78, "Ä")
	      PRINT #AREATXT, "Suma i continua..."
	      PRINT #AREATXT, RTRIM$(ARCHIMP.NOCOMPRIMIDO) + STRING$(78, "Ä")
	      PRINT #AREATXT, RTRIM$(ARCHIMP.SALTOPAGINA)
	      PAG = PAG + 1
	      GOSUB CAPSA
	   END IF
	END IF
	
	IF LIN$(L, 6) = "*" THEN
	   SELECT CASE MODO
		  CASE 0
		       PRINT #AREATXT, USING " \                \"; LIN$(L, 1);
		       PRINT #AREATXT, RTRIM$(ARCHIMP.COMPRIMIDO); LIN$(L, 2); RTRIM$(ARCHIMP.NOCOMPRIMIDO);
		       PRINT #AREATXT, USING "##,###  "; VAL(LIN$(L, 4));
		       PRINT #AREATXT, USING "   ###,###"; VAL(LIN$(L, 3));
		       PRINT #AREATXT, USING "  ##"; VAL(LIN$(L, 7));
		       PRINT #AREATXT, USING "   ##,###,###"; VAL(LIN$(L, 5))
		  CASE 1
		       PRINT #AREATXT, USING "          ##,###   "; VAL(LIN$(L, 4));
		       PRINT #AREATXT, RTRIM$(ARCHIMP.COMPRIMIDO); LIN$(L, 2); RTRIM$(ARCHIMP.NOCOMPRIMIDO);
		       PRINT #AREATXT, USING " ##,###,###   "; VAL(LIN$(L, 5))
		  CASE 2
		       PRINT #AREATXT, USING "\                \"; LIN$(L, 1);
		       PRINT #AREATXT, RTRIM$(ARCHIMP.COMPRIMIDO); LIN$(L, 2); RTRIM$(ARCHIMP.NOCOMPRIMIDO);
		       PRINT #AREATXT, USING "##,###.#"; VAL(LIN$(L, 4));
		       PRINT #AREATXT, USING " #,##,###"; VAL(LIN$(L, 3));
		       PRINT #AREATXT, USING "  ##"; VAL(LIN$(L, 7));
		       PRINT #AREATXT, USING "    ##,###,###   "; VAL(LIN$(L, 5))
		  CASE 3
		       PRINT #AREATXT, USING " \             \"; LIN$(L, 1);
		       PRINT #AREATXT, RTRIM$(ARCHIMP.COMPRIMIDO); LIN$(L, 2); RTRIM$(ARCHIMP.NOCOMPRIMIDO);
		       PRINT #AREATXT, USING "#,###.#"; VAL(LIN$(L, 4));
		       PRINT #AREATXT, USING " ##,###"; VAL(LIN$(L, 3));
		       PRINT #AREATXT, USING " ##"; VAL(LIN$(L, 7));
		       PRINT #AREATXT, USING " #####"; VAL(LIN$(L, 5))
		  CASE 4
		       PRINT #AREATXT, USING " \                \"; LIN$(L, 1);
		       PRINT #AREATXT, RTRIM$(ARCHIMP.COMPRIMIDO); LIN$(L, 2); RTRIM$(ARCHIMP.NOCOMPRIMIDO);
		       PRINT #AREATXT, USING "##,###.#"; VAL(LIN$(L, 4));
		       PRINT #AREATXT, USING "###,###   "; VAL(LIN$(L, 3));
		       PRINT #AREATXT, USING "  ##"; VAL(LIN$(L, 7));
		       PRINT #AREATXT, USING "   ##,###,###"; VAL(LIN$(L, 5))
		  CASE ELSE
	   END SELECT
	END IF
	L = L + 1: LI = LI + 1
    LOOP UNTIL LIN$(L, 6) = "-"

    FOR LA = LI TO MAXLINS: PRINT #AREATXT, "": NEXT
    SELECT CASE CASO%
	   CASE 1
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, USING " SUBTOTAL: ##,###,###.##"; PRESUPO.TOTALBRUT
		PRINT #AREATXT, USING " DTO%....:            ##"; PRESUPO.DTO;
		PRINT #AREATXT, USING SPACE$(24) + "BASE IMPONIBLE: ##,###,###.##"; PRESUPO.BASEIMPONIBLE
		PRINT #AREATXT, USING SPACE$(48) + "     IVA ## %.: ##,###,###.##"; PRESUPO.TIPOIVA; PRESUPO.TOTALIVA
		PRINT #AREATXT, ""
		PRINT #AREATXT, USING SPACE$(48) + "      TOTAL...: ##,###,###.##"; PRESUPO.TOTALNET
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, " " + "Forma de pagament: "; PRESUPO.PERSONA.FORMAPAGO; "  Observacions: " + RTRIM$(ARCHIMP.COMPRIMIDO);
		PRINT #AREATXT, RTRIM$(PRESUPO.OBSERVA(1)) + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		PRINT #AREATXT, "                                                     " + RTRIM$(ARCHIMP.COMPRIMIDO); RTRIM$(PRESUPO.OBSERVA(2)) + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, ""
	   CASE 2
		PRINT #AREATXT, " " + STRING$(78, "Ä")
		PRINT #AREATXT, USING SPACE$(48) + "     TOTAL...: ##,###,###.##"; PRESUPO.TOTALNET
		PRINT #AREATXT, " " + STRING$(78, "Ä")
		PRINT #AREATXT, " " + "Forma de pagament: "; PRESUPO.PERSONA.FORMAPAGO; "  Observacions: " + RTRIM$(ARCHIMP.COMPRIMIDO);
		PRINT #AREATXT, RTRIM$(PRESUPO.OBSERVA(1)) + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		PRINT #AREATXT, "                                                     " + RTRIM$(ARCHIMP.COMPRIMIDO); RTRIM$(PRESUPO.OBSERVA(2)) + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, ""
	   CASE 3
		PRINT #AREATXT, "" + RTRIM$(ARCHIMP.COMPRIMIDO)
		PRINT #AREATXT, ""
		PRINT #AREATXT, ""
		PRINT #AREATXT, ""
		PRINT #AREATXT, ""
		PRINT #AREATXT, ""
		PRINT #AREATXT, USING "##,###,###.##" + SPACE$(40) + "  ##,###,###.##     ##  ##,###,###.##     ## " + SPACE$(25) + "##,###,###.##"; PRESUPO.TOTALBRUT; PRESUPO.BASEIMPONIBLE; PRESUPO.TIPOIVA; PRESUPO.TOTALIVA; PRESUPO.DTO; PRESUPO. _
TOTALNET
		PRINT #AREATXT, "" + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		FOR I = 1 TO 8: PRINT #AREATXT, "": NEXT
		PRINT #AREATXT, "" + RTRIM$(ARCHIMP.COMPRIMIDO)
		PRINT #AREATXT, RTRIM$(PRESUPO.OBSERVA(1))
		PRINT #AREATXT, RTRIM$(PRESUPO.OBSERVA(2)) + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		PRINT #AREATXT, "Forma de pagament: "; PRESUPO.PERSONA.FORMAPAGO
	   CASE 4
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, USING " SUBTOTAL: ##,###,###.##"; PRESUPO.TOTALBRUT
		PRINT #AREATXT, USING " DTO%....:            ##"; PRESUPO.DTO;
		PRINT #AREATXT, USING SPACE$(26) + "BASE IMPONIBLE: ##,###,###.##"; PRESUPO.BASEIMPONIBLE
		PRINT #AREATXT, USING SPACE$(50) + "     IVA ## %.: ##,###,###.##"; PRESUPO.TIPOIVA; PRESUPO.TOTALIVA
		PRINT #AREATXT, ""
		PRINT #AREATXT, USING SPACE$(50) + "      TOTAL...: ##,###,###.##"; PRESUPO.TOTALNET
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, " " + "Forma de pagament: "; PRESUPO.PERSONA.FORMAPAGO; "  Observacions: " + RTRIM$(ARCHIMP.COMPRIMIDO);
		PRINT #AREATXT, RTRIM$(PRESUPO.OBSERVA(1)) + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		PRINT #AREATXT, "                                                     " + RTRIM$(ARCHIMP.COMPRIMIDO); RTRIM$(PRESUPO.OBSERVA(2)) + RTRIM$(ARCHIMP.NOCOMPRIMIDO)
		PRINT #AREATXT, " " + STRING$(78, "Ä")
		PRINT #AREATXT, ""
	   CASE 5
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, "SUBTOTAL:     BASE IMPONIBLE:   DTO%:  IVA%:      TOTAL IVA: TOTAL PRESUPOST:"
		PRINT #AREATXT, USING "###,###.##     ###,###.##        ##      ##   ##,###,###.##    #,###,###.##"; PRESUPO.TOTALBRUT; PRESUPO.BASEIMPONIBLE; PRESUPO.DTO; PRESUPO.TIPOIVA; PRESUPO.TOTALIVA; PRESUPO.TOTALNET
		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, "Forma de pagament: "; PRESUPO.PERSONA.FORMAPAGO
		FOR L = 1 TO 16: PRINT #AREATXT, "": NEXT
	   CASE ELSE
    END SELECT

    CLOSE #AREATXT

    COLOR 31, 9: LOCATE 11, 31: PRINT "  IMPRIMINT  "
    COLOR 31, 9: LOCATE 13, 31: PRINT "   FITXERS   "
    
    IF IMPR$ = "IMPRIMEIX_TEXTE" THEN ImprimeixFitxerTXT DIRECCT$ + "PRESUPO.TXT", DEVI$, 100
    PutBackground 1, 1, FACTU$
    EXIT SUB

CAPSA:
    PRINT #AREATXT, RTRIM$(ARCHIMP.ENSANCHADO) + RTRIM$(CAP.LINIES(0)) + RTRIM$(ARCHIMP.NOENSANCHADO)
    FOR I = 1 TO 4: PRINT #AREATXT, CAP.LINIES(I): NEXT
    SELECT CASE MODO
	   CASE 2
		PRINT #AREATXT, ""
		PRINT #AREATXT, ""
		PRINT #AREATXT, "" + SPACE$(34) + RTRIM$(ARCHIMP.ENSANCHADO) + "Presupost: " + PRESUPO.REFPRESUPO + RTRIM$(ARCHIMP.NOENSANCHADO)
		PRINT #AREATXT, "              Data:         Codi Client:      " + PRESUPO.PERSONA.NOM + RTRIM$(ARCHIMP.NEGRITA)
		PRINT #AREATXT, "           " + SPACE$(5) + PRESUPO.DADA + SPACE$(6) + PRESUPO.CODCLIENT + RTRIM$(ARCHIMP.NONEGRITA);
		PRINT #AREATXT, SPACE$(8) + PRESUPO.PERSONA.COGNOMS
		PRINT #AREATXT, SPACE$(42) + "    D.N.I. " + PRESUPO.PERSONA.DNI
		PRINT #AREATXT, "P…gina N§:"; SPACE$(34) + "  " + PRESUPO.PERSONA.DIRECCIO + RTRIM$(ARCHIMP.NEGRITA)
		PRINT #AREATXT, USING "\  \       \ \"; LTRIM$(STR$(PAG)); RTRIM$(ARCHIMP.NONEGRITA);
		PRINT #AREATXT, SPACE$(34) + LTRIM$(RTRIM$(PRESUPO.PERSONA.POBLACIO)) + " " + PRESUPO.PERSONA.CPOSTAL
		PRINT #AREATXT, SPACE$(45) + " Tels." + PRESUPO.PERSONA.TELEFON1
		PRINT #AREATXT, SPACE$(45) + "      " + PRESUPO.PERSONA.TELEFON2

		PRINT #AREATXT, ""
		PRINT #AREATXT, ""
		PRINT #AREATXT, CONFIG$(OPC)
		PRINT #AREATXT, ""
	   CASE ELSE
		PRINT #AREATXT, "                                   " + RTRIM$(ARCHIMP.ENSANCHADO) + "Presupost: " + PRESUPO.REFPRESUPO + RTRIM$(ARCHIMP.NOENSANCHADO)
		PRINT #AREATXT, "                 Data:      Codi Client:";
		PRINT #AREATXT, "     Ú" + SPACE$(31) + "¿" + RTRIM$(ARCHIMP.NEGRITA)
		PRINT #AREATXT, "          " + SPACE$(7) + PRESUPO.DADA + SPACE$(3) + PRESUPO.CODCLIENT + RTRIM$(ARCHIMP.NONEGRITA);
		PRINT #AREATXT, SPACE$(8) + " " + PRESUPO.PERSONA.NOM
		PRINT #AREATXT, "           " + SPACE$(34) + "  " + PRESUPO.PERSONA.COGNOMS
		PRINT #AREATXT, " P…gina N§:"; SPACE$(34) + "  D.N.I. " + PRESUPO.PERSONA.DNI + RTRIM$(ARCHIMP.NEGRITA)
		PRINT #AREATXT, USING " \  \       \ \"; LTRIM$(STR$(PAG)); RTRIM$(ARCHIMP.NONEGRITA);
		PRINT #AREATXT, SPACE$(32) + "  " + PRESUPO.PERSONA.DIRECCIO
		PRINT #AREATXT, SPACE$(47) + LTRIM$(RTRIM$(PRESUPO.PERSONA.POBLACIO)) + " " + PRESUPO.PERSONA.CPOSTAL
		PRINT #AREATXT, SPACE$(47) + "Tels." + PRESUPO.PERSONA.TELEFON1
		PRINT #AREATXT, SPACE$(47) + "     " + PRESUPO.PERSONA.TELEFON2
		PRINT #AREATXT, SPACE$(45) + "À" + SPACE$(31) + "Ù"

		PRINT #AREATXT, STRING$(78, "Ä")
		PRINT #AREATXT, CONFIG$(OPC)
		PRINT #AREATXT, STRING$(78, "Ä")
    END SELECT
    RETURN
END SUB

FUNCTION IniciaRef (AREANUM, R, MARCAT, REFOLD$)
	  DIM OP$(1 TO 10)

	  GET AREANUM, 1, DOCNUM
	  MAXDOC% = DOCNUM.MAXNUM
	  FOR RE = 1 TO MAXDOC%: OP$(RE) = DOCNUM.FACTNUM(RE).CONFACT: NEXT
	  CALL Menu2(OP$(), CASO%, 10, 10, LEN(OP$(1)) + 2, MAXDOC%, COL(0, 0), COL(0, 1), COL(1, 0), COL(1, 1))

	  IF CASO% = 999 OR CASO% = 888 THEN
	     IniciaRef = CASO%
	     ERASE OP$
	     EXIT FUNCTION
	  ELSE
	     REF$ = DOCNUM.FACTNUM(CASO%).NUMFACT
	     ALB$ = LTRIM$(STR$(DOCNUM.FACTNUM(CASO%).MAXFACT))
	  END IF

	  L2 = 6
	  FOR L = LEN(ALB$) TO 1 STEP -1
	      MID$(REF$, L2, 1) = MID$(ALB$, L, 1): L2 = L2 - 1
	  NEXT
	  MID$(REF$, 1, 2) = MID$(FormatD$(Now#, "dd/mm/yy"), 7, 2)

	  IniciaRef = CASO%
	  FACTURA.REFFACTURA = REF$
	  ERASE OP$
END FUNCTION

SUB INITPRESUPO (MAXLIN)

    PRESUPO.REFPRESUPO = CHR$(0)               ' INCIAR PRESUPO
    PRESUPO.CODCLIENT = CHR$(0)
    PRESUPO.DADA = FormatD$(Now#, "dd/mm/yy")
    PRESUPO.PERSONA.CODICLIENT = CHR$(0)
    PRESUPO.PERSONA.NOM = CHR$(0)
    PRESUPO.PERSONA.COGNOMS = CHR$(0)
    PRESUPO.PERSONA.DNI = CHR$(0)
    PRESUPO.PERSONA.POBLACIO = CHR$(0)
    PRESUPO.PERSONA.TELEFON1 = CHR$(0)
    PRESUPO.PERSONA.TELEFON2 = CHR$(0)
    PRESUPO.PERSONA.DTO = 0
    PRESUPO.PERSONA.FORMAPAGO = CHR$(0)
    PRESUPO.PERSONA.CPOSTAL = CHR$(0)
    PRESUPO.PERSONA.BANC = ""
    PRESUPO.PERSONA.COMPTE = ""

    PRESUPO.TOTALBRUT = 0
    PRESUPO.BASEIMPONIBLE = 0
    PRESUPO.TIPOIVA = 0
    PRESUPO.TOTALIVA = 0
    PRESUPO.DTO = 0
    PRESUPO.TOTALNET = 0
    TOTAL = 0
    FOR J = 1 TO MAXLIN
	LINPRES.LINIA(J).CODART = CHR$(0)
	LINPRES.LINIA(J).CONCEPTE = CHR$(0)
	LINPRES.LINIA(J).PREU = 0
	LINPRES.LINIA(J).QUANTI = 0
	LINPRES.LINIA(J).DTO = 0
	LINPRES.LINIA(J).IMPORT = 0
	LINPRES.LINIA(J).MARCAR = CHR$(0)
	LIN$(J, 1) = "": LIN$(J, 2) = "": LIN$(J, 3) = ""
	LIN$(J, 4) = "": LIN$(J, 5) = "": LIN$(J, 6) = "": LIN$(J, 7) = ""
    NEXT

END SUB

SUB LLISTARPRESUPO (AREA5, AREA2, DEVI$)
    SHARED DIRECCT$

    AREATXT = FREEFILE
    OPEN DIRECCT$ + "PRESUPOS.TXT" FOR OUTPUT AS AREATXT

    PAG = 1: L = 1
    GET AREA5, 1, CAP   ' AGAFAR CAP€ALERA DEL FITXER DE CAP€ALERES

    GOSUB CAP.LIST     ' IMPRIMIR CAP€ALERA

    ' DEFINIR MASCARA DE LES LINIES
    MASCARA$ = "  \" + SPACE$(9) + "\\" + SPACE$(47) + "\    ##,###,###.## ##.## ##.## ##,###,###.## \ \"
    MAXL = 54: TOTALB& = 0: TOTALN& = 0
    FOR R = 1 TO CEMPRE.MAXPRESUPO - 1
	GET AREA2, R, PRESUPO
	GOSUB PRINTLINIA
	TOTALB& = TOTALB& + PRESUPO.TOTALBRUT
	TOTALN& = TOTALN& + PRESUPO.TOTALNET
	IF L >= MAXL THEN
	   L = 1
	   PAG = PAG + 1
	   PRINT #AREATXT, RTRIM$(ARCHIMP.NOCOMPRIMIDO) + " " + STRING$(80, "Ä") + RTRIM$(ARCHIMP.COMPRIMIDO)
	   PRINT #AREATXT, RTRIM$(ARCHIMP.SALTOPAGINA)
	   GOSUB CAP.LIST
	END IF
    NEXT
    PRINT #AREATXT, RTRIM$(ARCHIMP.NOCOMPRIMIDO) + " " + STRING$(80, "Ä") + RTRIM$(ARCHIMP.COMPRIMIDO)
    PRINT #AREATXT, USING MASCARA$; SPACE$(9); SPACE$(31) + "Suma dels Totals: "; TOTALB&; 0; 0; TOTALN&

    PRINT #AREATXT, RTRIM$(ARCHIMP.SALTOPAGINA)
    PRINT #AREATXT, RTRIM$(ARCHIMP.NOCOMPRIMIDO)
    CLOSE #AREATXT
    
    CALL ImprimeixFitxerTXT(DIRECCT$ + "PRESUPOS.TXT", DEVI$, 180)' DIRECCIONAR EL FITXER CAP A LA IMPRESORA
    EXIT SUB

' **************************************************************************
' DEFINIR CAP€ALERA DELS LLISTATS
' **************************************************************************

CAP.LIST:
    PRINT #AREATXT, " "; RTRIM$(ARCHIMP.ENSANCHADO) + CAP.LINIES(0) + RTRIM$(ARCHIMP.NOENSANCHADO)
    PRINT #AREATXT, ""
    PRINT #AREATXT, " LLISTAT DELS PRESUPOSTS"
    PRINT #AREATXT, " P…gina:"; PAG
    PRINT #AREATXT, " Data..:"; FormatD$(Now#, "dd-mm-yyyy")
    PRINT #AREATXT, " " + STRING$(80, "Ä");
    PRINT #AREATXT, RTRIM$(ARCHIMP.COMPRIMIDO) + ""
    PRINT #AREATXT, "  ReferŠncia Nom del client                                          Subtotal   DTO % IVA % Total Net     Facturat"
    PRINT #AREATXT, "  ---------- ------------------------------------------------------- ---------- ----- ----- ------------- --------"
    RETURN

PRINTLINIA:
    NOMPCLIENT$ = RTRIM$(PRESUPO.PERSONA.COGNOMS) + ";" + RTRIM$(PRESUPO.PERSONA.NOM)
    IF PRESUPO.DOCUMENT = "F" THEN MARCA$ = "X" ELSE MARCA$ = ""
    PRINT #AREATXT, USING MASCARA$; PRESUPO.REFPRESUPO; NOMPCLIENT$; PRESUPO.TOTALBRUT; PRESUPO.DTO; PRESUPO.TIPOIVA; PRESUPO.TOTALNET; MARCA$
    L = L + 1
    RETURN
END SUB

SUB MASCALBA (MAX)

COLOR COL(0, 0), COL(0, 1)
FINESTRA 1, 1, 25, 80, 0, CAIXA1
COLOR COL(2, 0)
LOCATE , , 1, 13, 14
LOCATE 2, 2: PRINT "Presupost N—mero:"; SPACE$(11); "Document...: "; : COLOR 15: PRINT DOCU$; : COLOR COL(2, 0): PRINT "    M…xim de linies:"; : COLOR COL(0, 0): PRINT MAX: COLOR COL(2, 0)
LOCATE 4, 2: PRINT "Ref. Presup.:"
LOCATE 3, 27: PRINT "Codi Client:            Data:"
LOCATE 4, 27: PRINT "Nom........:"
LOCATE 5, 27: PRINT "Cognoms....:"
COLOR COL(0, 0)

LOCATE 20, 40: PRINT "DTO.%  LINIA:"

LOCATE 6, 1: PRINT "ÌÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÍÍÍ¹"
LOCATE 7, 1: PRINT "º Codi Article     ºConcepte                     ºPreu     ºQuant.  ºImport    º"
LOCATE 8, 1: PRINT "ÌÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÎÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÎÍÍÍÍÍÍÍÍÍÎÍÍÍÍÍÍÍÍÎÍÍÍÍÍÍÍÍÍÍ¹"
LOCATE 19, 1: PRINT "ÌÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÍÍÍ¹"
FOR L = 9 TO 18: LOCATE L, 2: PRINT SPACE$(18); "º"; SPACE$(29); "º"; SPACE$(9); "º"; SPACE$(8); "º": NEXT
LOCATE 20, 61: PRINT "Total:"
LOCATE 21, 2: PRINT STRING$(78, "Í");
COLOR 3, COL(0, 1)
LOCATE 20, 67: PRINT USING "##,###,###.##"; TOTAL
END SUB

SUB MASCALBS
    COLOR COL(0, 0), COL(0, 1): FINESTRA 4, 1, 20, 80, 0, CAIXA1
    LOCATE 5, 2: PRINT "ReferŠnciaºClient" + SPACE$(21) + "ºTotal brut   ºDTO% ºIVA% ºTotal Net"
    LOCATE 6, 1: PRINT "Ì"; STRING$(78, "Í"); "¹"
    LOCATE 4, 12: PRINT "Ë": LOCATE 4, 40: PRINT "Ë": LOCATE 4, 54: PRINT "Ë": LOCATE 4, 60: PRINT "Ë": LOCATE 4, 66: PRINT "Ë"
    LOCATE 6, 12: PRINT "Î": LOCATE 6, 40: PRINT "Î": LOCATE 6, 54: PRINT "Î": LOCATE 6, 60: PRINT "Î": LOCATE 6, 66: PRINT "Î"
    LOCATE 20, 12: PRINT "Ê": LOCATE 20, 40: PRINT "Ê": LOCATE 20, 54: PRINT "Ê": LOCATE 20, 60: PRINT "Ê": LOCATE 20, 66: PRINT "Ê"
    FINESTRA 21, 1, 25, 80, 0, CAIXA1
    LOCATE 22, 2: PRINT "<ENTER>=MODIFICAR PRESUPOST <F2>=INSERTAR PRESUPOST <" + CHR$(25) + ">=BAIXAR   <" + CHR$(24) + ">=PUJAR"
    LOCATE 23, 2: PRINT "<ESC>=SORTIR                <F3>=SUMAR PRESUPOST    <F4>=CONSULTAR"
    LOCATE 24, 2: PRINT "<F5>=MARCAR PRESUPOST       <F6>=LLISTAR            <F7>=IMPRIMIR";
END SUB

SUB OrdenarIndex (INDEX() AS INDEXTYPE, MAXST) STATIC
    OFFSET = MAXST - 1 \ 2
    DO WHILE OFFSET > 0
       LIMIT = MAXST - 1 - OFFSET
       DO
	 SWITCH = FALSE
	 FOR I = 1 TO LIMIT
	     IF INDEX(I).CODI > INDEX(I + OFFSET).CODI THEN
		SWAP INDEX(I), INDEX(I + OFFSET)
		SWITCH = I
	     END IF
	 NEXT

	 LIMIT = SWITCH
       LOOP WHILE SWITCH
       OFFSET = OFFSET \ 2
    LOOP
END SUB

FUNCTION POSSAESPAI$ (CAD$, C)
	 FOR L = 1 TO LEN(CAD$)
	     IF MID$(CAD$, L, 1) = CHR$(C) THEN MID$(CAD$, L, 1) = CHR$(32)
	 NEXT
	 POSSAESPAI$ = CAD$
END FUNCTION

SUB PresupostsEdit (MAX, DTO, IVA, DIRECC$, DIRCP$, DIRECI$, DH$, DP$, DEVI$, IMPRESORA)

    ON ERROR GOTO ERRORS

    GOSUB OBRIFITXERS
    MASCALBS                          ' PINTA LA MASCARA DE LA LLISTA
    DIM NDXFILE AS INDEXTYPE
    X = 7: R = 1: L = 1: R = 1

    DIRECCT$ = DIRCP$

    SetScoreBoard SON                 ' ACTIVA EL VISOR D'ESTAT DE LES TECLES D'ESTAT

    GOSUB FINAL.NOU
    DO
      OP$ = INKEY$
      COLOR COL(0, 0), COL(0, 1): CALL EstatTeclesControl(25, 3)
      SELECT CASE OP$
	     CASE CHR$(0) + "P"      ' BAIXA UN REGISTRE
		  GOSUB BAIXACURSOR
	     CASE CHR$(0) + "H"      ' PUJA UN REGISTRE
		  GOSUB PUJACURSOR
	     CASE CHR$(27)
		  SetScoreBoard SOFF: RESET
		  EXIT SUB
	     CASE CHR$(13)
		  CALL CrearPRESUPOSTs(MAX, DTO, IVA, AREANUM, AREA3, AREA2, AREA4, AREAST, MAXFA, MAXST, MAXPR, 1, DH$, DEVI$)
		  MASCALBS
		  X = 7: R = 1: GOSUB LISTA: X = 7: R = 1: GET AREA2, R, PRESUPO: COLCURS = COL(1, 1): GOSUB SHOWCURSOR
	     CASE CHR$(0) + CHR$(60)
		  CALL CrearPRESUPOSTs(MAX, DTO, IVA, AREANUM, AREA3, AREA2, AREA4, AREAST, MAXFA, MAXST, MAXPR, 0, DH$, DEVI$)
		  MASCALBS
		  X = 7: R = 1: GOSUB LISTA: X = 7: R = 1: GET AREA2, R, PRESUPO: COLCURS = COL(1, 1): GOSUB SHOWCURSOR
	     CASE CHR$(0) + CHR$(61)
		  SUMARPRESUPOS MAXPR, AREA2
	     CASE CHR$(0) + CHR$(63)
		  GOSUB DELETERECORD         ' MARCAR REGISTRE
	     CASE CHR$(0) + CHR$(64)
		  GetBackground 1, 1, 24, 79, FACTU$
		  CALL LLISTARPRESUPO(AREA5, AREA2, DEVI$)
		  PutBackground 1, 1, FACTU$
	     CASE CHR$(0) + CHR$(65)
		  CALL CARREGARPRESUPO(R, MAX)
		  CALL IMPRIMIRPRESUPO(MAX, DEVI$)
	     CASE CHR$(0) + "Q"
		  GOSUB BOTA.AVALL
	     CASE CHR$(0) + "I"
		  GOSUB BOTA.AMUNT
		  GET AREA2, R, FACTURA: COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
	     CASE ELSE
      END SELECT
   LOOP
   RETURN

FINAL.NOU:
    IF MAXPR > 13 THEN
       R = MAXPR - 5: L = 1: X = 7
       GOSUB LISTA
       X = 7 + 4: R = MAXPR - 1                  ' INICIA CURSOR I POSICIONS A PANTALLA
    ELSE
       X = 7: R = 1: GOSUB LISTA: X = 7: R = 1
    END IF
    GET AREA2, R, PRESUPO: COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR

    RETURN
'************************************************************************
' Control del cursor per el llistat amb despla‡ament de barres
'************************************************************************

' ********* Avan‡ de p…gines (AMUNT/AVALL) *********

BOTA.AVALL:
   IF R = MAXPR - 1 THEN RETURN
   GOSUB ANAR.TOPE: S = 1
   DO
	S = S + 1
	IF RB + S > MAXPR - 1 THEN
	   WHILE (RB + S > MAXPR - 1)
		 S = S - 1
	   WEND
	   EXIT DO
	END IF
   LOOP UNTIL S = 13
   RB = RB + S: R = RB: RESTA = 0: GOSUB LISTA
   GOSUB ANAR.TOPE
   GET AREA2, RB, PRESUPO: X = XB
   COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR: R = RB
   RETURN

BOTA.AMUNT:
   IF R = 1 THEN RETURN
   GOSUB ANAR.TOPE
   S = 1
   DO
	S = S + 1
	IF RB - S < 1 THEN
	   WHILE (RB - S < 1)
		 S = S - 1
	   WEND
	   EXIT DO
	END IF
   LOOP UNTIL S = 13
   RB = RB - S: R = RB: GOSUB LISTA
   GOSUB ANAR.TOPE
   GET AREA2, RB, PRESUPO: X = XB
   COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
   R = RB
   RETURN

ANAR.TOPE:
   XB = X: RB = R         ' Guarda l'estat actual
   DO UNTIL XB = 7
       XB = XB - 1        ' Resta l'estat actual fins arribar al tope del recuadre
       RB = RB - 1
   LOOP
   RETURN

'************************************************************************
' Control del cursor per el llistat amb despla‡ament de barres
' funci¢ parescuda al DBEDIT de Clipper.
'************************************************************************

PUJACURSOR:
       IF X = 7 THEN
	  GET AREA2, R, PRESUPO
	  COLOR COL(0, 0), COL(0, 1): GOSUB SHOWCURSOR
	  IF R = 1 THEN
	     X = 7: R = 1
	     COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
	     RETURN
	  END IF
	  R = R - 1: X = 7
	  ScrollDown 18, 78, 6, 1, 1
	  GET AREA2, R, PRESUPO
	  COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
       ELSE
	  GET AREA2, R, PRESUPO
	  COLOR COL(0, 0), COL(0, 1): GOSUB SHOWCURSOR
	  R = R - 1: X = X - 1
	  GET AREA2, R, PRESUPO
	  COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
       END IF
       RETURN

BAIXACURSOR:
       IF X = 19 THEN
	  GET AREA2, R, PRESUPO
	  COLOR COL(0, 0), COL(0, 1): GOSUB SHOWCURSOR
	  IF R = MAXPR - 1 THEN
	     R = MAXPR - 1
	     X = 19
	     COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
	     RETURN
	  END IF
	  R = R + 1: X = 19
	  ScrollUp 18, 78, 6, 1, 1
	  GET AREA2, R, PRESUPO
	  COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
       ELSE
	  GET AREA2, R, PRESUPO
	  COLOR COL(0, 0), COL(0, 1): GOSUB SHOWCURSOR
	  IF R = MAXPR - 1 THEN
	     R = MAXPR - 1
	     COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
	     RETURN
	  END IF
	  R = R + 1: X = X + 1
	  GET AREA2, R, PRESUPO
	  COLOR COL(1, 0), COL(1, 1): GOSUB SHOWCURSOR
       END IF
       RETURN

'************************************************************************
' Mostra el cursor a la posici¢ que est…
'************************************************************************

SHOWCURSOR:
	  IF PRESUPO.MARCAT = "*" THEN C = 27 ELSE C = 15
	  LOCATE X, 2: PRINT PRESUPO.REFPRESUPO; " º"; PRESUPO.PERSONA.NOM; ","; MID$(PRESUPO.PERSONA.COGNOMS, 1, 6); "º";
	  PRINT USING "##,###,###.##º##.##º##.##º##,###,###.##"; PRESUPO.TOTALBRUT; PRESUPO.DTO; PRESUPO.TIPOIVA; PRESUPO.TOTALNET
	  RETURN

LISTA:
    IF MAXPR = 1 THEN
       NOU = 2: Avis.Sonor (1)
       tecla = Avis("AVIS:", "No hi ha cap presupost creat, ara es procedir… a crear-ne un", "Pitji una tecla...", 0)
       CALL CrearPRESUPOSTs(MAX, DTO, IVA, AREANUM, AREA3, AREA2, AREA4, AREAST, MAXFA, MAXST, MAXPR, 0, DH$, DEVI$)
       IF NOU = 9 THEN
	  RESET
	  EXIT SUB
       END IF
       MASCALBS
       X = 7: R = 1: GOSUB LISTA: COLCURS = COL(0, 1): GOSUB SHOWCURSOR
    END IF

    COLOR COL(0, 0), COL(0, 1)
    FOR X = 7 TO 19: LOCATE X, 2: PRINT "          º                           º             º     º     º             ": NEXT
    FOR X = 7 TO 19
       IF R = MAXPR THEN EXIT FOR
       GET AREA2, R, PRESUPO
       COLOR COL(0, 0), COL(0, 1): GOSUB SHOWCURSOR
       R = R + 1
    NEXT
    RETURN

DELETERECORD:
    GET AREA2, R, PRESUPO
    IF PRESUPO.MARCAT = " " THEN
       PRESUPO.MARCAT = "*"
       PUT AREA2, R, PRESUPO
    ELSE
       PRESUPO.MARCAT = " "
       PUT AREA2, R, PRESUPO
    END IF

    GET AREA2, R, PRESUPO
    COLCURS = COL(1, 1): GOSUB SHOWCURSOR
    RETURN

OBRIFITXERS:
      AREA = FREEFILE: OPEN DIRECC$ + "CONTROL.DSF" FOR RANDOM SHARED AS AREA LEN = LEN(CEMPRE)
      AREA2 = FREEFILE: OPEN DIRECC$ + "PRESUPO.CAB" FOR RANDOM SHARED AS AREA2 LEN = LEN(PRESUPO)
      AREA3 = FREEFILE: OPEN DIRECC$ + "PRESUPO.LIN" FOR RANDOM SHARED AS AREA3 LEN = LEN(LINPRES)
      AREA4 = FREEFILE: OPEN DIRECC$ + "CLIENTS.DAT" FOR RANDOM SHARED AS AREA4 LEN = LEN(CLIENT)
      AREA5 = FREEFILE: OPEN DP$ + "PLANTILL\CAP€ALER.DAT" FOR RANDOM SHARED AS AREA5 LEN = LEN(CAP)
      AREAST = FREEFILE: OPEN DIRECC$ + "STOCK.DAT" FOR RANDOM SHARED AS AREAST LEN = LEN(STOCK)
      AREANDX = FREEFILE: OPEN DIRECC$ + "STOCK.NDX" FOR RANDOM SHARED AS AREANDX LEN = LEN(NDXFILE)
      AREANUM = FREEFILE: OPEN DIRECC$ + "DOCUMENT.NUM" FOR RANDOM SHARED AS AREANUM LEN = LEN(DOCNUM)

'*********************************************************************
' DEMANAR IMPRESORA ACTIVA
'*********************************************************************
      AREA6 = FREEFILE: OPEN "..\SPOOL.CFG" FOR RANDOM SHARED AS AREA6 LEN = LEN(SPOOLIMP)
      GET AREA6, IMPRESORA, SPOOLIMP
      FITXER$ = LTRIM$(RTRIM$(SPOOLIMP.ARCHIVO))
      CLOSE AREA6

'*********************************************************************
' OBRIR FITXER DE LA IMPRESORA
'*********************************************************************

      AREA7 = FREEFILE: OPEN DIRECI$ + FITXER$ FOR RANDOM SHARED AS AREA7 LEN = LEN(ARCHIMP)
      GET AREA7, 1, ARCHIMP
      CLOSE AREA7

'*********************************************************************
' INICIAR EL CONTROL DELS REGISTRES
'*********************************************************************
      GET AREA, 1, CEMPRE
      IF CEMPRE.MAXPRESUPO = 0 THEN
	 CEMPRE.MAXPRESUPO = 1
	 PUT AREA, 1, CEMPRE
      END IF
      MAXFA = CEMPRE.MAXFACTURA
      MAXCL = CEMPRE.MAXCLIENTS
      MAXST = CEMPRE.MAXSTOCK
      MAXPR = CEMPRE.MAXPRESUPO
      RETURN

END SUB

SUB ReadCalculFactura
  GetBackground 1, 1, 24, 79, RESBUF$
  COLOR 1, 3
  FINESTRA 9, 10, 14, 60, 1, CAIXA1

  COLOR COL(2, 0), 3
  LOCATE 10, 12: PRINT "Subtotal:"; : COLOR 15: PRINT PRESUPO.TOTALBRUT; : COLOR 14
  LOCATE 13, 33: PRINT "      Total:"; : COLOR 15: PRINT PRESUPO.TOTALNET; : COLOR 14
  LOCATE 10, 33: PRINT "Descompte %:"; : COLOR 15: PRINT PRESUPO.DTO; : COLOR 14
  LOCATE 11, 33: PRINT "      IVA %:"; : COLOR 15: PRINT PRESUPO.TIPOIVA;
  SetMaxCamps 1

  SetColorCamp 0, 15, 1, 15, 3, 14, 3
  SetColorCamp 1, 15, 1, 15, 3, 14, 3

  InsertValueCamp 0, LTRIM$(STR$(PRESUPO.DTO))
  InsertValueCamp 1, LTRIM$(STR$(PRESUPO.TIPOIVA))
  SetInitCamp 0, 10, 45, NUM, 0, "999", ""
  SetInitCamp 1, 11, 45, NUM, 0, "999", ""
  IF ReadCamp(0) = SALIR THEN EXIT SUB
  IF ReadCamp(1) = SALIR THEN EXIT SUB
  
  PRESUPO.DTO = VAL(ValueCamp$(0))
  PRESUPO.TIPOIVA = VAL(ValueCamp$(1))

  'PRESUPO.BASEIMPONIBLE=TOTAL        ' NO HI HA DESCOMPTE

   PRESUPO.BASEIMPONIBLE = PRESUPO.TOTALBRUT - (PRESUPO.TOTALBRUT * PRESUPO.DTO) / 100
   BASEIMP = PRESUPO.BASEIMPONIBLE
   IVA = BASEIMP * (PRESUPO.TIPOIVA) / 100
   PRESUPO.TOTALIVA = IVA
   PRESUPO.TOTALNET = BASEIMP + IVA

   COLOR 14: LOCATE 13, 33: PRINT "      Total:";
   COLOR 15: PRINT USING "##,###,###.##"; PRESUPO.TOTALNET; : COLOR 14

  'PRESUPO.BASEIMPONIBLE = PRESUPO.TOTALBRUT - PRESUPO.DTO

END SUB

SUB READCAPSALERA (MAXPR, MAXCL)
       DIM LLISTA$(MAXCL - 1)
       FOR C = 0 TO 10: DeleteCamp C: NEXT C

       REPINTACAPSALERA (MAXPR)
       FOR C = 0 TO 4
	   VALUE = ReadCamp(C)
	   SELECT CASE VALUE
		  CASE 1
		       TROBAT = 0
		       FOR R = 1 TO MAXCL
			   GET AREA4, R, CLIENT
			   IF ValueCamp$(1) = CLIENT.CODICLIENT THEN
			      InsertValueCamp 3, CLIENT.NOM
			      InsertValueCamp 4, CLIENT.COGNOMS
			      PRESUPO.PERSONA.NOM = CLIENT.NOM
			      PRESUPO.PERSONA.COGNOMS = CLIENT.COGNOMS
			      PRESUPO.PERSONA.DNI = CLIENT.DNI
			      PRESUPO.PERSONA.DIRECCIO = CLIENT.DIRECCIO
			      PRESUPO.PERSONA.POBLACIO = CLIENT.POBLACIO
			      PRESUPO.PERSONA.TELEFON1 = CLIENT.TELEFON1
			      PRESUPO.PERSONA.TELEFON2 = CLIENT.TELEFON2
			      PRESUPO.PERSONA.CPOSTAL = CLIENT.CPOSTAL
			      PRESUPO.PERSONA.DTO = CLIENT.DTO
			      PRESUPO.PERSONA.FORMAPAGO = CLIENT.FORMAPAGO
			      TROBAT = 44
			      EXIT FOR
			   END IF
		       NEXT
			   IF TROBAT = 44 THEN
			      DisplayAllCamps
			      PRESUPO.REFPRESUPO = ValueCamp$(0)
			      PRESUPO.CODCLIENT = ValueCamp$(1)
			   END IF
		  CASE F1
		       'CALL (DIRECCP$, DIRECCF$, DIRECCI$, DBF$, DEV$, IMPRESORA, MAXLINS)
		       C = C - 1
		  CASE F2
		       IF C = 1 THEN GOSUB LLISTA.CLIENTS
		       C = C - 1
		  CASE F3 TO F10
		       C = C - 1
		  CASE 999
		       EXIT SUB
		  CASE ELSE
	   END SELECT
       NEXT
       PRESUPO.DADA = ValueCamp$(2)
       ERASE LLISTA$
       EXIT SUB

LLISTA.CLIENTS:
       IF MAXCL = 1 THEN
	  tecla = Avis("AVIS:", "La base de dades dels clients est… buida", "Pitja una tecla...", 0)
	  RETURN
       END IF

       GetBackground 1, 1, 24, 79, LISBUF$
       SetScoreBoard SOFF: LOCATE , , 0: R = 1
       FOR Q = 1 TO MAXCL - 1
	   GET AREA4, R, CLIENT
	   IF CLIENT.MARCAT = "-" THEN
	      CODI$ = CLIENT.CODICLIENT
	      N$ = LTRIM$(RTRIM$(CLIENT.NOM))
	      C$ = LTRIM$(RTRIM$(CLIENT.COGNOMS))
	      S$ = N$ + " " + C$: NOM$ = MID$(S$, 1, 40)
	      LLISTA$(R) = CODI$ + " " + NOM$
	      R = R + 1
	   END IF
       NEXT

       ASEL = Achoice(3, 9, 20, 61, R - 1, LLISTA$(), COL(), "Codi       Nom                                     ", 12, LTRIM$(RTRIM$(ValueCamp$(3))))
       IF ASEL = 0 OR ASEL = -14 OR ASEL = -13 THEN
	  PutBackground 1, 1, LISBUF$
	  C = C - 1: RETURN
       END IF
       IF ASEL <= 0 THEN ASEL = 1
       GET AREA4, ASEL, CLIENT
       InsertValueCamp 1, CLIENT.CODICLIENT
       CALL DisplayAllCamps: C = C - 1
       PutBackground 1, 1, LISBUF$
       RETURN

END SUB

SUB ReadObserva
    SHARED OBS$()
    LOCATE 22, 2: PRINT SPACE$(70);
    LOCATE 23, 2: PRINT SPACE$(70);
    LOCATE 24, 2: PRINT SPACE$(70);

    SetMaxCamps 1
    SetColorCamp 0, COL(1, 0), COL(1, 1), COL(0, 0), COL(0, 1), COL(2, 0), COL(2, 1)
    SetColorCamp 1, COL(1, 0), COL(1, 1), COL(0, 0), COL(0, 1), COL(2, 0), COL(2, 1)
    
    SetInitCamp 0, 22, 20, ASCI, 0, STRING$(50, "X"), ""
    SetInitCamp 1, 23, 20, ASCI, 0, STRING$(50, "X"), ""

    COLOR COL(0, 0) XOR COL(0, 1), COL(0, 1)
    LOCATE 24, 2: PRINT "ENTER=SORTIR";
    LOCATE 22, 2: PRINT "Observacions: ";
    InsertValueCamp 0, PRESUPO.OBSERVA(1): InsertValueCamp 1, PRESUPO.OBSERVA(2)

    IF ReadCamp(0) = SALIR THEN
       OBS$(0) = ValueCamp$(0)
       EXIT SUB
    END IF
    IF ReadCamp(1) = SALIR THEN
       OBS$(1) = ValueCamp$(1)
       EXIT SUB
    END IF
    OBS$(0) = ValueCamp$(0)
    OBS$(1) = ValueCamp$(1)
    PRESUPO.OBSERVA(1) = OBS$(0)
    PRESUPO.OBSERVA(2) = OBS$(1)
    LOCATE 22, 2: PRINT SPACE$(70);
    LOCATE 23, 2: PRINT "ENTER=EDITAR LINIA    ESC=ANULAR    SUPR=SUPRIMIR LINIA";
    LOCATE 24, 2: PRINT "<" + CHR$(25) + ">= BAIXAR           <" + CHR$(24) + ">= PUJAR    CTRL+F=ACABAR DE FACTURAR";
END SUB

SUB REPINTACAPSALERA (MAX)
       FOR C = 0 TO 10: DeleteCamp C: NEXT C

       SetMaxCamps 4
       FOR C = 0 TO 4: SetColorCamp C, COL(1, 0), COL(1, 1), COL(0, 0), COL(0, 1), COL(2, 0), COL(2, 1): NEXT

       SetInitCamp 0, 4, 15, ASCI, 0, "XXXXXXXXX", ""
       SetInitCamp 1, 3, 39, ASCI, 0, "XXXXXXXXXX", ""
       SetInitCamp 2, 3, 56, NUM, 0, "99/99/99", ""
       SetInitCamp 3, 4, 39, ASCI, 0, STRING$(20, "X"), ""
       SetInitCamp 4, 5, 39, ASCI, 0, STRING$(30, "X"), ""

       COLOR 15: LOCATE 2, 18: PRINT R

       InsertValueCamp 0, PRESUPO.REFPRESUPO
       InsertValueCamp 1, PRESUPO.CODCLIENT
       InsertValueCamp 2, PRESUPO.DADA
       InsertValueCamp 3, PRESUPO.PERSONA.NOM
       InsertValueCamp 4, PRESUPO.PERSONA.COGNOMS
       DisplayAllCamps

END SUB

SUB SUMARPRESUPOS (MAXPR, AREA2)
	   GetBackground 1, 1, 24, 79, FACTU$
	   COLOR COL(0, 0), COL(0, 1): FINESTRA 9, 10, 16, 60, 1, CAIXA1: COLOR COL(2, 0), COL(2, 1)
	   FOR S = 1 TO MAXPR
	       GET AREA2, S, PRESUPO
	       SUMABRUTS = SUMABRUTS + PRESUPO.TOTALBRUT
	       SUMABI = SUMABI + PRESUPO.BASEIMPONIBLE
	       SUMANET = SUMANET + PRESUPO.TOTALNET
	   NEXT
	   LOCATE 10, 11: PRINT "Suma dels totals:"
	   LOCATE 12, 11: PRINT "Subtotals.......:"; : COLOR COL(0, 0), COL(0, 1)
	   PRINT USING "##,###,###.##"; SUMABRUTS:  COLOR COL(2, 0), COL(2, 1)
	   LOCATE 13, 11: PRINT "Bases Imponibles:"; : COLOR COL(0, 0), COL(0, 1)
	   PRINT USING "##,###,###.##"; SUMABI:  COLOR COL(2, 0), COL(2, 1)
	   LOCATE 14, 11: PRINT "IVA's...........:"; : COLOR COL(0, 0), COL(0, 1)
	   PRINT USING "##,###,###.##"; SUMABI:  COLOR COL(2, 0), COL(2, 1)
	   LOCATE 15, 11: PRINT "Totals Net......:"; : COLOR COL(0, 0), COL(0, 1)
	   PRINT USING "##,###,###.##"; SUMANET: COLOR COL(2, 0), COL(2, 1)
	   C$ = INPUT$(1)
	   PutBackground 1, 1, FACTU$

END SUB

