GESTIO.EXE:      FACTUR20.OBJ
                 LINK /FAR /NOE /NOD:BRT71EFR.LIB   \
                 FACTUR20,             \
                 GESTIO.EXE,,          \
                 BCL71EFR.LIB+         \
                 QBX.LIB+              \
                 DRACLIB.LIB;

