
'$INCLUDE: 'C:\FACT3\FONTS\FACTURA.BI'

TYPE LINFAC2                        ' DEFINICI¢ DELS CAMPS EN UNA LINIA DE L'ALBARAN
     CODART AS STRING * 18
     CONCEPTE AS STRING * 40
     PREU AS LONG
     QUANTI AS SINGLE
     DTO AS INTEGER
     IMPORT AS LONG
     MARCAR AS STRING * 1
END TYPE

TYPE LINIE2                           ' DEFINICI¢ DE LINIES DE L'ALBARAN
     LINIA(1 TO 100) AS LINFAC2
END TYPE

DIM LINALBA AS LINIES
DIM LINALB2 AS LINIE2

PRINT "Conversor a decimals 1.0"
AREA2T = FREEFILE: OPEN "ALBARAN.LIN" FOR RANDOM SHARED AS AREA2T LEN = LEN(LINALBA)
AREA2C = FREEFILE: OPEN "ALBARAN.NOU" FOR RANDOM SHARED AS AREA2C LEN = LEN(LINALB2)

MAXREG = LOF(AREA2T) \ LEN(LINALBA)

FOR R = 1 TO MAXREG
    GET AREA2T, R, LINALBA
    
    PRINT "--------------------------------------------------------->" + STR$(R)
    FOR L = 1 TO 100
        
        LINALB2.LINIA(L).CODART = LINALBA.LINIA(L).CODART
        LINALB2.LINIA(L).CONCEPTE = LINALBA.LINIA(L).CONCEPTE
        LINALB2.LINIA(L).PREU = LINALBA.LINIA(L).PREU
        LINALB2.LINIA(L).QUANTI = LINALBA.LINIA(L).QUANTI
        LINALB2.LINIA(L).DTO = LINALBA.LINIA(L).DTO
        LINALB2.LINIA(L).IMPORT = LINALBA.LINIA(L).IMPORT
        LINALB2.LINIA(L).MARCAR = LINALBA.LINIA(L).MARCAR
        IF LINALB2.LINIA(L).QUANTI <> 0 THEN
           PRINT LINALB2.LINIA(L).QUANTI, LINALB2.LINIA(L).CONCEPTE
        END IF

    NEXT
    PUT AREA2C, R, LINALB2
NEXT

CLOSE AREA2T, AREA2C
RESET
END

