
'$INCLUDE: 'C:\FACT3\FONTS\FACTURA.BI'

TYPE LINFACTUR2
     REFALBARAN AS STRING * 9
     CODART AS STRING * 18
     CONCEPTE AS STRING * 40
     PREU AS LONG
     QUANTI AS SINGLE
     DTO AS INTEGER
     IMPORT AS LONG
     MARCAR AS STRING * 1
END TYPE

TYPE LINIAFAC2
     LINIA(1 TO 100) AS LINFACTUR2
END TYPE

DIM LINFACT AS LINIAFACT
DIM LINFAC2 AS LINIAFAC2


PRINT "Conversor a decimals 1.0"
AREA2T = FREEFILE: OPEN DIRECC$ + "FACTURES.LIN" FOR RANDOM SHARED AS AREA2T LEN = LEN(LINFACT)
AREA2C = FREEFILE: OPEN DIRECC$ + "FACTURES.NOU" FOR RANDOM SHARED AS AREA2C LEN = LEN(LINFAC2)
MAXREG = LOF(AREA2T) \ LEN(LINFACT)

FOR R = 1 TO MAXREG
    GET AREA2T, R, LINFACT
    FOR L = 1 TO 100
        LINFAC2.LINIA(L).REFALBARAN = LINFACT.LINIA(L).REFALBARAN
        LINFAC2.LINIA(L).CODART = LINFACT.LINIA(L).CODART
        LINFAC2.LINIA(L).CONCEPTE = LINFACT.LINIA(L).CONCEPTE
        LINFAC2.LINIA(L).PREU = LINFACT.LINIA(L).PREU
        LINFAC2.LINIA(L).QUANTI = LINFACT.LINIA(L).QUANTI
        LINFAC2.LINIA(L).DTO = LINFACT.LINIA(L).DTO
        LINFAC2.LINIA(L).IMPORT = LINFACT.LINIA(L).IMPORT
        LINFAC2.LINIA(L).MARCAR = LINFACT.LINIA(L).MARCAR
    NEXT
    PUT AREA2C, R, LINFAC2
NEXT

CLOSE AREA2T, AREA2C
RESET
END

