'$INCLUDE: 'structs.bi'

DIM ANYS AS anno

AREAA = FREEFILE: OPEN "ANYS.DAT" FOR RANDOM SHARED AS AREAA LEN = LEN(ANYS)

ANYS.CPY = "YEARS" + CHR$(27)
ANYS.ANY = "1999"
ANYS.DATAO = DATE$
ANYS.HORAO = TIME$
ANYS.DATAT = ""
ANYS.HORAT = ""
PUT AREAA, 1, ANYS

CLOSE AREAA

