
'$INCLUDE: 'QBX.BI'
'$INCLUDE: 'DATIM.BI'
'$INCLUDE: 'FORMAT.BI'
'$INCLUDE: 'C:\FACT3\FONTS\STRUCTS.BI'
'$INCLUDE: 'C:\FACT3\FONTS\FACTURA.BI'
'$INCLUDE: 'C:\FACT3\FONTS\STOCK.BI'
'$INCLUDE: 'C:\FACT3\FONTS\SDK_001.BI'
'$INCLUDE: 'C:\FACT3\FONTS\DRAC3.BI'
'$INCLUDE: 'C:\FACT3\FONTS\CONSTS.BI'

DIM TD AS TIPUSDOC
DIM USR AS USUARIS

      OPEN "C:\FACT3\USUARIS.FAC" FOR RANDOM SHARED AS 5 LEN = LEN(USR)

      GET 5, 1, USR
      USR.MODEIMPRES = 1
      PUT 5, 1, USR
      CLOSE 5

      'AREADOC = FREEFILE: OPEN "C:\FACT3\FACTU001\PLANTILL\FAC_MSK.LST" FOR RANDOM SHARED AS AREADOC LEN = LEN(TD)
      'TD.DESCRIPCIO = "  DOCUMENT TIPUS PER DEFECTE     ": TD.FITXER = "F_DEFE.DAT": PUT AREADOC, 1, TD
      'TD.DESCRIPCIO = "  DOCUMENT TIPUS 1               ": TD.FITXER = "F_TIP1.DAT": PUT AREADOC, 2, TD
      'TD.DESCRIPCIO = "  DOCUMENT AMB PAPER PRE-IMPRES  ": TD.FITXER = "F_PREI.DAT": PUT AREADOC, 3, TD
      'TD.DESCRIPCIO = "  DOCUMENT COMPACTAT (RESGUARDS) ": TD.FITXER = "F_CRES.DAT": PUT AREADOC, 4, TD
      'TD.DESCRIPCIO = "  DOCUMENT TIPUS COMPACTE        ": TD.FITXER = "F_COMP.DAT": PUT AREADOC, 5, TD
      'CLOSE AREADOC

