DECLARE FUNCTION ENCRIPT$ (CAD$, CARENC%)

FUNCTION ENCRIPT$ (CAD$, CARENC%)
    MAXLEN% = LEN(CAD$)
    ENCRIPT$ = SPACE$(MAXLEN%)
    FOR P = 1 TO MAXLEN%
        MID$(ENCRIPT$, P, 1) = CHR$(ASC(MID$(CAD$, P, 1)) XOR CARENC%)
    NEXT
END FUNCTION

