
'$INCLUDE: 'QBX.BI'
'$INCLUDE: 'C:\FACT2\FONTS\DMOUSE.BI'
'$INCLUDE: 'C:\FACT2\FONTS\CAMPS.BI'
'$INCLUDE: 'C:\FACT2\FONTS\STRUCTS.BI'
'$INCLUDE: 'C:\FACT2\FONTS\WIN.BI'

FUNCTION DIALOG (TIM)

DO
 MouseOn
 FOR I = 0 TO MAXBOTS  ' ESCANETJA TOTS EL PUNTS DEFINITS COM A BOTONS
     C$ = INKEY$
     X = BOTS(I).RECT.X
     Y = BOTS(I).RECT.Y
     X2 = BOTS(I).RECT.X2
     Y2 = BOTS(I).RECT.Y2

     CT1 = BOTS(B).COLORS.CTITOL1
     CT2 = BOTS(B).COLORS.CTITOL2
     CP1 = BOTS(B).COLORS.CCAMP1
     CP2 = BOTS(B).COLORS.CCAMP2

     IF MouseRegion(X, Y, X2, Y2) THEN
	EXIT FOR
     END IF

     IF C$ = CHR$(27) THEN
	DIALOG = 999
	EXIT FUNCTION
     END IF
 NEXT
 
 IF MouseRegion(X, Y, X2, Y2) AND MouseDown(1) THEN
    V = 1
    DO
       IF MouseRegion(X, Y, X2, Y2) THEN
	 IF V = 1 THEN
	    MouseOff
	    X% = X: Y% = Y: X2% = X2: Y2% = Y2
	    COLOR CT2, CT2: FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1
	    COLOR CP1, CP2: FINESTRA X%, Y% + 1, X2%, Y2% + 1, 0, CAIXA1
	    'COLOR CT2: BOX X%, Y%, X2%, Y2%
	    'COLOR CP1, CP2: BOX X%, Y% + 1, X2%, Y2% + 1
	    LOCATE X + 1, Y + 2: PRINT LTRIM$(RTRIM$(BOTS(I).TITOL));
	    MouseOn
	  V = 0
	 END IF
       ELSE
	 IF V = 0 THEN
	  MouseOff
	  X% = X: Y% = Y: X2% = X2: Y2% = Y2
	  COLOR CT2, CT2: FINESTRA X%, Y%, X2%, Y2% + 1, 0, CAIXA1
	  COLOR CT1, CT2: FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1
	  LOCATE X + 1, Y + 1: PRINT LTRIM$(RTRIM$(BOTS(I).TITOL));
	  MouseOn
	  V = 1
	 END IF
       END IF
    LOOP UNTIL MouseDown(0)

    IF MouseRegion(X, Y, X2, Y2) THEN
       EXIT DO
    END IF
 END IF
LOOP

MouseOff
	  X% = X: Y% = Y: X2% = X2: Y2% = Y2
	  COLOR CT2, CT2: BOX X%, Y% + 1, X2%, Y2% + 1
	  COLOR CT1, CT2: FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1
	  LOCATE X + 1, Y + 1: PRINT RTRIM$(LTRIM$(BOTS(I).TITOL));

MouseOn

DIALOG = I
END FUNCTION

SUB SETBOTOCOLOR (CT1, CT2, CP1, CP2, B)
    BOTS(B).COLORS.CTITOL1 = CT1
    BOTS(B).COLORS.CTITOL2 = CT2

    BOTS(B).COLORS.CCAMP1 = CP1
    BOTS(B).COLORS.CCAMP2 = CP2

END SUB

REM $DYNAMIC
SUB SETBOTOXY (X, Y, X2, Y2, B)
    BOTS(B).RECT.X = X
    BOTS(B).RECT.Y = Y
    BOTS(B).RECT.X2 = X2
    BOTS(B).RECT.Y2 = Y2
END SUB

SUB SETMAXBOTONS (MAX)
    MAXBOTS = MAX
END SUB

SUB SHOWBOTO (TITOL$, B)

    X% = BOTS(B).RECT.X
    Y% = BOTS(B).RECT.Y
    X2% = BOTS(B).RECT.X2
    Y2% = BOTS(B).RECT.Y2
    BOTS(B).TITOL = TITOL$
    CT1 = BOTS(B).COLORS.CTITOL1
    CT2 = BOTS(B).COLORS.CTITOL2
    CP1 = BOTS(B).COLORS.CCAMP1
    CP2 = BOTS(B).COLORS.CCAMP2

    COLOR CT2: BOX X%, Y% + 1, X2%, Y2% + 1
    COLOR CT1, CT2

    FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1
    LOCATE X% + 1, Y% + 1: PRINT TITOL$;

END SUB

