'
' WIN_001.BAS
'
' Llibreria per iniciar les noves biblioteques Smart Libs. 4.x
' Llibreria per gestionar finestres i events
' 1997 (C)
' Tomeu Cap¢ Cap¢ 1997 (C)
' Smart Software 1993/97 (C)
'

'$INCLUDE: 'QBX.BI'
'$INCLUDE: 'D:\FACT3\FONTS\DMOUSE.BI'
'$INCLUDE: 'D:\FACT3\FONTS\DRAC3.BI'
'$INCLUDE: 'D:\FACT3\FONTS\SDK_001.BI'
'$INCLUDE: 'D:\FACT3\FONTS\WIN.BI'

REM $DYNAMIC
FUNCTION DeleteBoto (B)
      IF B > MAXCREATEB OR B < 0 THEN
	 DeleteBoto = TRUE
	 EXIT FUNCTION
      ELSE
	 BOTS(B).MARCAT = "*"
	 DeleteBoto = FALSE
	 EXIT FUNCTION
      END IF
END FUNCTION

SUB DeleteWindow (FIN)
      X% = WINDOWS(FIN).RECT.X
      Y% = WINDOWS(FIN).RECT.Y
      X2% = WINDOWS(FIN).RECT.X2
      Y2% = WINDOWS(FIN).RECT.Y2
      SH = WINDOWS(FIN).SHADOW
      T$ = LTRIM$(RTRIM$(WINDOWS(FIN).TITOL))

      WINDOWS(FIN).MARCADA = "*"
      PutBackground X%, Y%, WINDOWS(FIN).buffer
END SUB

FUNCTION Dialog

  CAIXA1$ = "…Õª∫»Õº"
  CAIXA2$ = "⁄ƒø≥¿ƒŸ"

DO
 MouseOn
 FOR I = 0 TO MAXCREATEB - 1 ' ESCANETJA TOTS EL PUNTS DEFINITS COM A BOTONS
     C$ = INKEY$
     X = BOTS(I).RECT.X
     Y = BOTS(I).RECT.Y
     X2 = BOTS(I).RECT.X2
     Y2 = BOTS(I).RECT.Y2

     CT1 = BOTS(B).COLORS.CTITOL1
     CT2 = BOTS(B).COLORS.CTITOL2
     CP1 = BOTS(B).COLORS.CCAMP1
     CP2 = BOTS(B).COLORS.CCAMP2

     IF MouseRegion(X, Y, X2, Y2) THEN
	EXIT FOR
     END IF

     IF C$ = CHR$(27) THEN
	Dialog = 999
	EXIT FUNCTION
     END IF
 NEXT

 IF MouseRegion(X, Y, X2, Y2) AND MouseDown(1) THEN
    V = 1
    DO
       IF MouseRegion(X, Y, X2, Y2) THEN
	 IF V = 1 THEN
	    MouseOff
	    X% = X: Y% = Y: X2% = X2: Y2% = Y2
	    COLOR CT2, CT2: FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1$
	    COLOR CP1, CP2: FINESTRA X%, Y% + 1, X2%, Y2% + 1, 0, CAIXA1$
	    LOCATE X + 1, Y + 2: PRINT LTRIM$(RTRIM$(BOTS(I).TITOL));
	    MouseOn
	    V = 0
	 END IF
       ELSE
	 IF V = 0 THEN
	    MouseOff
	    X% = X: Y% = Y: X2% = X2: Y2% = Y2
	    COLOR CT2, CT2: FINESTRA X%, Y%, X2%, Y2% + 1, 0, CAIXA1$
	    COLOR CT1, CT2: FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1$
	    LOCATE X + 1, Y + 1: PRINT LTRIM$(RTRIM$(BOTS(I).TITOL));
	    MouseOn
	    V = 1
	 END IF
       END IF
    LOOP UNTIL MouseDown(0)

    IF MouseRegion(X, Y, X2, Y2) THEN
       EXIT DO
    END IF
 END IF
LOOP

	  MouseOff
	  X% = X: Y% = Y: X2% = X2: Y2% = Y2
	  COLOR CT2, CT2: FINESTRA X%, Y% + 1, X2%, Y2% + 1, 0, CAIXA2$
	  COLOR CT1, CT2: FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1$
	  LOCATE X + 1, Y + 1: PRINT RTRIM$(LTRIM$(BOTS(I).TITOL));
	  MouseOn
	  Dialog = I

END FUNCTION

FUNCTION InitNewWindow (WIND, X%, Y%, X2%, Y2%, SHADOW, TITOL$)

	 IF MAXCREATE > MAXWINDOWS THEN
	    InitNewWindow = TRUE
	    EXIT FUNCTION
	 END IF

	 WINDOWS(WIND).RECT.X = X%
	 WINDOWS(WIND).RECT.Y = Y%
	 WINDOWS(WIND).RECT.X2 = X2%
	 WINDOWS(WIND).RECT.Y2 = Y2%
	 WINDOWS(WIND).TITOL = TITOL$
	 WINDOWS(WIND).SHADOW = SHADOW
	 WINDOWS(WIND).MARCADA = "-"
	 
	 MAXCREATE = MAXCREATE + 1
	 InitNewWindow = FALSE
END FUNCTION

SUB OutTextLN (FIN, TEXT$)

    X = WINDOWS(FIN).RECT.X + 1
    Y = WINDOWS(FIN).RECT.Y + 1
    X2 = WINDOWS(FIN).RECT.X2 - 1
    Y2 = WINDOWS(FIN).RECT.Y2 - 1


    PrintByWord X, Y, X2, Y2, (WINDOWS(FIN).COLORS.CTITOL1), (WINDOWS(FIN).COLORS.CTITOL2), TEXT$
END SUB

SUB PackBotons

    FOR B = 0 TO MAXCREATEB - 1
	IF BOTS(B).MARCAT = "-" THEN
	   BOTS(R).RECT.X = BOTS(B).RECT.X
	   BOTS(R).RECT.Y = BOTS(B).RECT.Y
	   BOTS(R).RECT.X2 = BOTS(B).RECT.X2
	   BOTS(R).RECT.Y2 = BOTS(B).RECT.Y2
	   BOTS(R).COLORS.CTITOL1 = BOTS(B).COLORS.CTITOL1
	   BOTS(R).COLORS.CTITOL1 = BOTS(B).COLORS.CTITOL2
	   BOTS(R).COLORS.CTITOL1 = BOTS(B).COLORS.CCAMP1
	   BOTS(R).COLORS.CTITOL1 = BOTS(B).COLORS.CCAMP2
	   BOTS(R).COLORS.CTITOL1 = BOTS(B).COLORS.CTEXT1
	   BOTS(R).COLORS.CTITOL1 = BOTS(B).COLORS.CTEXT2
	   BOTS(R).TITOL = BOTS(B).TITOL
	   R = R + 1
	END IF
     NEXT

     REDIM PRESERVE BOTS(0 TO R) AS GEST
     MAXCREATEB = R
END SUB

SUB PackWindows
    FOR W = 0 TO MAXCREATE - 1
	IF WINDOWS(W).MARCADA = "-" THEN
	   WINDOWS(R).RECT.X = WINDOWS(W).RECT.X
	   WINDOWS(R).RECT.Y = WINDOWS(W).RECT.Y
	   WINDOWS(R).RECT.X2 = WINDOWS(W).RECT.X2
	   WINDOWS(R).RECT.Y2 = WINDOWS(W).RECT.Y2
	   WINDOWS(R).COLORS.CTITOL1 = WINDOWS(W).COLORS.CTITOL1
	   WINDOWS(R).COLORS.CTITOL1 = WINDOWS(W).COLORS.CTITOL2
	   WINDOWS(R).COLORS.CTITOL1 = WINDOWS(W).COLORS.CCAMP1
	   WINDOWS(R).COLORS.CTITOL1 = WINDOWS(W).COLORS.CCAMP2
	   WINDOWS(R).COLORS.CTITOL1 = WINDOWS(W).COLORS.CTEXT1
	   WINDOWS(R).COLORS.CTITOL1 = WINDOWS(W).COLORS.CTEXT2
	   WINDOWS(R).buffer = WINDOWS(W).buffer
	   WINDOWS(R).TITOL = WINDOWS(W).TITOL
	   WINDOWS(R).SHADOW = WINDOWS(W).SHADOW
	   WINDOWS(R).STYLE = WINDOWS(W).STYLE
	   WINDOWS(R).MYSTYLE = WINDOWS(W).MYSTYLE
	   R = R + 1
	END IF
     NEXT

     REDIM PRESERVE WINDOWS(0 TO R) AS WIN
     MAXCREATE = R
END SUB

REM $STATIC
SUB SetAllColors (titolt, titolf, fonst, fonsf, TEXTEt, TEXTEf)

FOR FIN = 0 TO MAXCREATE
    WINDOWS(FIN).COLORS.CCAMP1 = fonsf
    WINDOWS(FIN).COLORS.CCAMP2 = fonst
    WINDOWS(FIN).COLORS.CTEXT1 = titolt
    WINDOWS(FIN).COLORS.CTEXT2 = titolf
    WINDOWS(FIN).COLORS.CTITOL1 = TEXTEt
    WINDOWS(FIN).COLORS.CTITOL2 = TEXTEf
NEXT

END SUB

SUB SetBotoColor (CT1, CT2, CP1, CP2, B)
    BOTS(B).COLORS.CTITOL1 = CT1
    BOTS(B).COLORS.CTITOL2 = CT2
    BOTS(B).COLORS.CCAMP1 = CP1
    BOTS(B).COLORS.CCAMP2 = CP2
END SUB

SUB SetColorWindow (FIN, titolt, titolf, fonst, fonsf, TEXTEt, TEXTEf)
    WINDOWS(FIN).COLORS.CCAMP1 = fonsf
    WINDOWS(FIN).COLORS.CCAMP2 = fonst
    WINDOWS(FIN).COLORS.CTEXT1 = titolt
    WINDOWS(FIN).COLORS.CTEXT2 = titolf
    WINDOWS(FIN).COLORS.CTITOL1 = TEXTEt
    WINDOWS(FIN).COLORS.CTITOL2 = TEXTEf
END SUB

REM $DYNAMIC
FUNCTION SetInitBoto (X, Y, X2, Y2, TITOL$, B)

    IF MAXCREATEB > MAXBOTS THEN
       SetInitBoto = TRUE
       EXIT FUNCTION
    END IF


    BOTS(B).RECT.X = X
    BOTS(B).RECT.Y = Y
    BOTS(B).RECT.X2 = X2
    BOTS(B).RECT.Y2 = Y2
    BOTS(B).TITOL = TITOL$
    BOTS(B).MARCAT = "-"

    MAXCREATEB = MAXCREATEB + 1
    SetInitBoto = FALSE

END FUNCTION

REM $STATIC
FUNCTION SetInitWindows (MAX) STATIC
    MAXCREATE = 0
    MAXWINDOWS = MAX

    IF MAX > 65000 THEN
       SetInitWindows = TRUE
       EXIT FUNCTION
    END IF

    REDIM PRESERVE WINDOWS(0 TO MAX) AS WIN
    SetInitWindows = FALSE
END FUNCTION

FUNCTION SetMaxBotons (MAX)
    MAXCREATEB = 0
    MAXBOTS = MAX

    IF MAX > 65000 THEN
       SetMaxBotons = TRUE
       EXIT FUNCTION
    END IF

    REDIM PRESERVE BOTS(0 TO MAX) AS GEST
    SetMaxBots = FALSE
END FUNCTION

SUB SetStyleWindow (FIN, TIPUS, STYLE$)
    SELECT CASE TIPUS
	   CASE 0
		WINDOWS(FIN).STYLE = TIPUS
		WINDOWS(FIN).MYSTYLE = "…Õª∫»Õº"
	   CASE 1
		WINDOWS(FIN).STYLE = TIPUS
		WINDOWS(FIN).MYSTYLE = "⁄ƒø≥¿ƒŸ"
	   CASE 2
		WINDOWS(FIN).STYLE = TIPUS
		WINDOWS(FIN).MYSTYLE = "€€€€€€€"
	   CASE ELSE
		WINDOWS(FIN).STYLE = TIPUS
		WINDOWS(FIN).MYSTYLE = STYLE$

    END SELECT
END SUB

SUB ShowBoto (B)
    CAIXA1$ = "…Õª∫»Õº"
    CAIXA2$ = "⁄ƒø≥¿ƒŸ"

    X% = BOTS(B).RECT.X
    Y% = BOTS(B).RECT.Y
    X2% = BOTS(B).RECT.X2
    Y2% = BOTS(B).RECT.Y2
    TITOL$ = LTRIM$(RTRIM$(BOTS(B).TITOL))

    CT1 = BOTS(B).COLORS.CTITOL1
    CT2 = BOTS(B).COLORS.CTITOL2
    CP1 = BOTS(B).COLORS.CCAMP1
    CP2 = BOTS(B).COLORS.CCAMP2

    COLOR CT2: FINESTRA X%, Y% + 1, X2%, Y2% + 1, 0, CAIXA2$
    COLOR CT1, CT2

    FINESTRA X%, Y%, X2%, Y2%, 0, CAIXA1$
    LOCATE X% + 1, Y% + 1: PRINT TITOL$;

END SUB

SUB ShowWindow (FIN)

      X% = WINDOWS(FIN).RECT.X
      Y% = WINDOWS(FIN).RECT.Y
      X2% = WINDOWS(FIN).RECT.X2
      Y2% = WINDOWS(FIN).RECT.Y2
      SH = WINDOWS(FIN).SHADOW
      T$ = LTRIM$(RTRIM$(WINDOWS(FIN).TITOL))

      IF WINDOWS(FIN).SHADOW = 1 THEN
	 GetBackground X%, Y%, X2% + 1, Y2% + 1, WINDOWS(FIN).buffer
      ELSE
	 GetBackground X%, Y%, X2%, Y2%, WINDOWS(FIN).buffer
      END IF

      COLOR WINDOWS(FIN).COLORS.CTEXT1, WINDOWS(FIN).COLORS.CTEXT2
      FINESTRA X%, Y%, X2%, Y2%, SH, WINDOWS(FIN).MYSTYLE

      COLOR WINDOWS(FIN).COLORS.CTITOL1, WINDOWS(FIN).COLORS.CTITOL2
      FINESTRA X% + 1, Y% + 1, X2% - 1, Y2% - 1, 0, "       "

      LENGHT = (Y2% - Y%) + 1

      TEXT$ = SPACE$(80): TEXT$ = MID$(T$, 1, LENGHT)

      COLOR WINDOWS(FIN).COLORS.CCAMP1, WINDOWS(FIN).COLORS.CCAMP2
      
      LOCATE X%, Y%: PRINT SPACE$(LENGHT);
      FOR L = 1 TO LEN(TEXT$)
	     P% = Y% + LENGHT \ 2 - L \ 2
	     IF P% < Y% + 1 THEN
	     ELSE
		CA$ = MID$(TEXT$, 1, L)
		LOCATE X%, P%: PRINT CA$;
	     END IF
      NEXT
      COLOR WINDOWS(FIN).COLORS.CTEXT1, WINDOWS(FIN).COLORS.CTEXT2
      LOCATE X%, Y%: PRINT CHR$(15);

END SUB

