
SET DATE BRITISH

USE C:\FACTURAS\ALMACEN.DBF ALIAS STOCK
INDEX ON ARTICULO TO STOCK

SET CONSOLE OFF
SET ALTERNATE TO STOCK.DAT
SET ALTERNATE ON

GO TOP
WHILE !EOF()
   @ 1,1 SAY "Important :"+ALLTRIM(STR(RECNO()))
   ?? STOCK->CODIGO
   ?? STOCK->ARTICULO
   ?? "0000000"
   ?? STOCK->PROVEEDOR
   ?? STOCK->EXISTENCIA
   ?? STOCK->PRECIO
   ?? STOCK->DESCUENTO
   ?? STOCK->PRECIO
   ?? "00"
   ?? STOCK->PVP_ACONSE
   ?? STOCK->IMPORTE
   ?? "00"
   ?? "000000000"
   ?? "000000000"
   ?? STOCK->EXISTENCIA
   ?? STOCK->FECHA_COMP
   ?? STOCK->FAMILIA
   ?? " "
   SKIP
END DO

SET ALTERNATE OFF
SET CONSOLE ON

CLOSE ALTERNATE
CLOSE DATABASE
